/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateAlertRecordPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRecordPayload{}

// UpdateAlertRecordPayload Record. `Additional Validators:` * total config (all alert groups/rules/records) should not be bigger than 500000 characters as string since this the limitation of prometheus.
type UpdateAlertRecordPayload struct {
	// The PromQL expression to evaluate. Every evaluation cycle this is evaluated at the current time, and all resultant time series become pending/firing alerts.
	Expr string `json:"expr"`
	// map of key:value. Labels to add or overwrite for each alert. `Additional Validators:` * should not contain more than 5 keys * each key and value should not be longer than 200 characters
	Labels map[string]interface{} `json:"labels,omitempty"`
}

type _UpdateAlertRecordPayload UpdateAlertRecordPayload

// NewUpdateAlertRecordPayload instantiates a new UpdateAlertRecordPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertRecordPayload(expr string) *UpdateAlertRecordPayload {
	this := UpdateAlertRecordPayload{}
	this.Expr = expr
	return &this
}

// NewUpdateAlertRecordPayloadWithDefaults instantiates a new UpdateAlertRecordPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertRecordPayloadWithDefaults() *UpdateAlertRecordPayload {
	this := UpdateAlertRecordPayload{}
	return &this
}

// GetExpr returns the Expr field value
func (o *UpdateAlertRecordPayload) GetExpr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expr
}

// GetExprOk returns a tuple with the Expr field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertRecordPayload) GetExprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expr, true
}

// SetExpr sets field value
func (o *UpdateAlertRecordPayload) SetExpr(v string) {
	o.Expr = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateAlertRecordPayload) GetLabels() map[string]interface{} {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertRecordPayload) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UpdateAlertRecordPayload) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *UpdateAlertRecordPayload) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

func (o UpdateAlertRecordPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertRecordPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expr"] = o.Expr
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *UpdateAlertRecordPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAlertRecordPayload := _UpdateAlertRecordPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateAlertRecordPayload)

	if err != nil {
		return err
	}

	*o = UpdateAlertRecordPayload(varUpdateAlertRecordPayload)

	return err
}

type NullableUpdateAlertRecordPayload struct {
	value *UpdateAlertRecordPayload
	isSet bool
}

func (v NullableUpdateAlertRecordPayload) Get() *UpdateAlertRecordPayload {
	return v.value
}

func (v *NullableUpdateAlertRecordPayload) Set(val *UpdateAlertRecordPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertRecordPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertRecordPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertRecordPayload(val *UpdateAlertRecordPayload) *NullableUpdateAlertRecordPayload {
	return &NullableUpdateAlertRecordPayload{value: val, isSet: true}
}

func (v NullableUpdateAlertRecordPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertRecordPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
