/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1api

import (
	"encoding/json"
	"fmt"
)

// checks if the MysqlCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlCheckResponse{}

// MysqlCheckResponse struct for MysqlCheckResponse
type MysqlCheckResponse struct {
	Message              string                    `json:"message"`
	MysqlCheck           *MysqlCheckChildResponse  `json:"mysqlCheck,omitempty"`
	MysqlChecks          []MysqlCheckChildResponse `json:"mysqlChecks"`
	AdditionalProperties map[string]interface{}
}

type _MysqlCheckResponse MysqlCheckResponse

// NewMysqlCheckResponse instantiates a new MysqlCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlCheckResponse(message string, mysqlChecks []MysqlCheckChildResponse) *MysqlCheckResponse {
	this := MysqlCheckResponse{}
	this.Message = message
	this.MysqlChecks = mysqlChecks
	return &this
}

// NewMysqlCheckResponseWithDefaults instantiates a new MysqlCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlCheckResponseWithDefaults() *MysqlCheckResponse {
	this := MysqlCheckResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *MysqlCheckResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MysqlCheckResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MysqlCheckResponse) SetMessage(v string) {
	o.Message = v
}

// GetMysqlCheck returns the MysqlCheck field value if set, zero value otherwise.
func (o *MysqlCheckResponse) GetMysqlCheck() MysqlCheckChildResponse {
	if o == nil || IsNil(o.MysqlCheck) {
		var ret MysqlCheckChildResponse
		return ret
	}
	return *o.MysqlCheck
}

// GetMysqlCheckOk returns a tuple with the MysqlCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlCheckResponse) GetMysqlCheckOk() (*MysqlCheckChildResponse, bool) {
	if o == nil || IsNil(o.MysqlCheck) {
		return nil, false
	}
	return o.MysqlCheck, true
}

// HasMysqlCheck returns a boolean if a field has been set.
func (o *MysqlCheckResponse) HasMysqlCheck() bool {
	if o != nil && !IsNil(o.MysqlCheck) {
		return true
	}

	return false
}

// SetMysqlCheck gets a reference to the given MysqlCheckChildResponse and assigns it to the MysqlCheck field.
func (o *MysqlCheckResponse) SetMysqlCheck(v MysqlCheckChildResponse) {
	o.MysqlCheck = &v
}

// GetMysqlChecks returns the MysqlChecks field value
func (o *MysqlCheckResponse) GetMysqlChecks() []MysqlCheckChildResponse {
	if o == nil {
		var ret []MysqlCheckChildResponse
		return ret
	}

	return o.MysqlChecks
}

// GetMysqlChecksOk returns a tuple with the MysqlChecks field value
// and a boolean to check if the value has been set.
func (o *MysqlCheckResponse) GetMysqlChecksOk() ([]MysqlCheckChildResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.MysqlChecks, true
}

// SetMysqlChecks sets field value
func (o *MysqlCheckResponse) SetMysqlChecks(v []MysqlCheckChildResponse) {
	o.MysqlChecks = v
}

func (o MysqlCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.MysqlCheck) {
		toSerialize["mysqlCheck"] = o.MysqlCheck
	}
	toSerialize["mysqlChecks"] = o.MysqlChecks

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MysqlCheckResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"mysqlChecks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMysqlCheckResponse := _MysqlCheckResponse{}

	err = json.Unmarshal(data, &varMysqlCheckResponse)

	if err != nil {
		return err
	}

	*o = MysqlCheckResponse(varMysqlCheckResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "mysqlCheck")
		delete(additionalProperties, "mysqlChecks")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMysqlCheckResponse struct {
	value *MysqlCheckResponse
	isSet bool
}

func (v NullableMysqlCheckResponse) Get() *MysqlCheckResponse {
	return v.value
}

func (v *NullableMysqlCheckResponse) Set(val *MysqlCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlCheckResponse(val *MysqlCheckResponse) *NullableMysqlCheckResponse {
	return &NullableMysqlCheckResponse{value: val, isSet: true}
}

func (v NullableMysqlCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
