/*
STACKIT DNS API

This api provides dns

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dns

type ZoneModelsExportRecordModel struct {
	Comment *string   `json:"comment,omitempty"`
	Content *[]string `json:"content,omitempty"`
	Name    *string   `json:"name,omitempty"`
	Ttl     *int64    `json:"ttl,omitempty"`
	Type    *string   `json:"type,omitempty"`
}
