/*
STACKIT Cost API

The cost API provides detailed reports on the costs for a customer or project over a certain amount of time

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cost

import (
	"encoding/json"
)

// checks if the SummarizedProjectCosts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummarizedProjectCosts{}

/*
	types and functions for customerAccountId
*/

// isNotNullableString
type SummarizedProjectCostsGetCustomerAccountIdAttributeType = *string

func getSummarizedProjectCostsGetCustomerAccountIdAttributeTypeOk(arg SummarizedProjectCostsGetCustomerAccountIdAttributeType) (ret SummarizedProjectCostsGetCustomerAccountIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setSummarizedProjectCostsGetCustomerAccountIdAttributeType(arg *SummarizedProjectCostsGetCustomerAccountIdAttributeType, val SummarizedProjectCostsGetCustomerAccountIdRetType) {
	*arg = &val
}

type SummarizedProjectCostsGetCustomerAccountIdArgType = string
type SummarizedProjectCostsGetCustomerAccountIdRetType = string

/*
	types and functions for projectId
*/

// isNotNullableString
type SummarizedProjectCostsGetProjectIdAttributeType = *string

func getSummarizedProjectCostsGetProjectIdAttributeTypeOk(arg SummarizedProjectCostsGetProjectIdAttributeType) (ret SummarizedProjectCostsGetProjectIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setSummarizedProjectCostsGetProjectIdAttributeType(arg *SummarizedProjectCostsGetProjectIdAttributeType, val SummarizedProjectCostsGetProjectIdRetType) {
	*arg = &val
}

type SummarizedProjectCostsGetProjectIdArgType = string
type SummarizedProjectCostsGetProjectIdRetType = string

/*
	types and functions for projectName
*/

// isNotNullableString
type SummarizedProjectCostsGetProjectNameAttributeType = *string

func getSummarizedProjectCostsGetProjectNameAttributeTypeOk(arg SummarizedProjectCostsGetProjectNameAttributeType) (ret SummarizedProjectCostsGetProjectNameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setSummarizedProjectCostsGetProjectNameAttributeType(arg *SummarizedProjectCostsGetProjectNameAttributeType, val SummarizedProjectCostsGetProjectNameRetType) {
	*arg = &val
}

type SummarizedProjectCostsGetProjectNameArgType = string
type SummarizedProjectCostsGetProjectNameRetType = string

/*
	types and functions for totalCharge
*/

// isDouble
type SummarizedProjectCostsGetTotalChargeAttributeType = *float64
type SummarizedProjectCostsGetTotalChargeArgType = float64
type SummarizedProjectCostsGetTotalChargeRetType = float64

func getSummarizedProjectCostsGetTotalChargeAttributeTypeOk(arg SummarizedProjectCostsGetTotalChargeAttributeType) (ret SummarizedProjectCostsGetTotalChargeRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setSummarizedProjectCostsGetTotalChargeAttributeType(arg *SummarizedProjectCostsGetTotalChargeAttributeType, val SummarizedProjectCostsGetTotalChargeRetType) {
	*arg = &val
}

/*
	types and functions for totalDiscount
*/

// isDouble
type SummarizedProjectCostsGetTotalDiscountAttributeType = *float64
type SummarizedProjectCostsGetTotalDiscountArgType = float64
type SummarizedProjectCostsGetTotalDiscountRetType = float64

func getSummarizedProjectCostsGetTotalDiscountAttributeTypeOk(arg SummarizedProjectCostsGetTotalDiscountAttributeType) (ret SummarizedProjectCostsGetTotalDiscountRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setSummarizedProjectCostsGetTotalDiscountAttributeType(arg *SummarizedProjectCostsGetTotalDiscountAttributeType, val SummarizedProjectCostsGetTotalDiscountRetType) {
	*arg = &val
}

// SummarizedProjectCosts Summarized costs for a project
type SummarizedProjectCosts struct {
	// REQUIRED
	CustomerAccountId SummarizedProjectCostsGetCustomerAccountIdAttributeType `json:"customerAccountId" required:"true"`
	// REQUIRED
	ProjectId SummarizedProjectCostsGetProjectIdAttributeType `json:"projectId" required:"true"`
	// REQUIRED
	ProjectName SummarizedProjectCostsGetProjectNameAttributeType `json:"projectName" required:"true"`
	// Total charge for all services and the whole requested date range (value in cents)
	// REQUIRED
	TotalCharge SummarizedProjectCostsGetTotalChargeAttributeType `json:"totalCharge" required:"true"`
	// Total discount for all services and the whole requested date range (value in cents)
	// REQUIRED
	TotalDiscount SummarizedProjectCostsGetTotalDiscountAttributeType `json:"totalDiscount" required:"true"`
}

type _SummarizedProjectCosts SummarizedProjectCosts

// NewSummarizedProjectCosts instantiates a new SummarizedProjectCosts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummarizedProjectCosts(customerAccountId SummarizedProjectCostsGetCustomerAccountIdArgType, projectId SummarizedProjectCostsGetProjectIdArgType, projectName SummarizedProjectCostsGetProjectNameArgType, totalCharge SummarizedProjectCostsGetTotalChargeArgType, totalDiscount SummarizedProjectCostsGetTotalDiscountArgType) *SummarizedProjectCosts {
	this := SummarizedProjectCosts{}
	setSummarizedProjectCostsGetCustomerAccountIdAttributeType(&this.CustomerAccountId, customerAccountId)
	setSummarizedProjectCostsGetProjectIdAttributeType(&this.ProjectId, projectId)
	setSummarizedProjectCostsGetProjectNameAttributeType(&this.ProjectName, projectName)
	setSummarizedProjectCostsGetTotalChargeAttributeType(&this.TotalCharge, totalCharge)
	setSummarizedProjectCostsGetTotalDiscountAttributeType(&this.TotalDiscount, totalDiscount)
	return &this
}

// NewSummarizedProjectCostsWithDefaults instantiates a new SummarizedProjectCosts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummarizedProjectCostsWithDefaults() *SummarizedProjectCosts {
	this := SummarizedProjectCosts{}
	return &this
}

// GetCustomerAccountId returns the CustomerAccountId field value
func (o *SummarizedProjectCosts) GetCustomerAccountId() (ret SummarizedProjectCostsGetCustomerAccountIdRetType) {
	ret, _ = o.GetCustomerAccountIdOk()
	return ret
}

// GetCustomerAccountIdOk returns a tuple with the CustomerAccountId field value
// and a boolean to check if the value has been set.
func (o *SummarizedProjectCosts) GetCustomerAccountIdOk() (ret SummarizedProjectCostsGetCustomerAccountIdRetType, ok bool) {
	return getSummarizedProjectCostsGetCustomerAccountIdAttributeTypeOk(o.CustomerAccountId)
}

// SetCustomerAccountId sets field value
func (o *SummarizedProjectCosts) SetCustomerAccountId(v SummarizedProjectCostsGetCustomerAccountIdRetType) {
	setSummarizedProjectCostsGetCustomerAccountIdAttributeType(&o.CustomerAccountId, v)
}

// GetProjectId returns the ProjectId field value
func (o *SummarizedProjectCosts) GetProjectId() (ret SummarizedProjectCostsGetProjectIdRetType) {
	ret, _ = o.GetProjectIdOk()
	return ret
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *SummarizedProjectCosts) GetProjectIdOk() (ret SummarizedProjectCostsGetProjectIdRetType, ok bool) {
	return getSummarizedProjectCostsGetProjectIdAttributeTypeOk(o.ProjectId)
}

// SetProjectId sets field value
func (o *SummarizedProjectCosts) SetProjectId(v SummarizedProjectCostsGetProjectIdRetType) {
	setSummarizedProjectCostsGetProjectIdAttributeType(&o.ProjectId, v)
}

// GetProjectName returns the ProjectName field value
func (o *SummarizedProjectCosts) GetProjectName() (ret SummarizedProjectCostsGetProjectNameRetType) {
	ret, _ = o.GetProjectNameOk()
	return ret
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *SummarizedProjectCosts) GetProjectNameOk() (ret SummarizedProjectCostsGetProjectNameRetType, ok bool) {
	return getSummarizedProjectCostsGetProjectNameAttributeTypeOk(o.ProjectName)
}

// SetProjectName sets field value
func (o *SummarizedProjectCosts) SetProjectName(v SummarizedProjectCostsGetProjectNameRetType) {
	setSummarizedProjectCostsGetProjectNameAttributeType(&o.ProjectName, v)
}

// GetTotalCharge returns the TotalCharge field value
func (o *SummarizedProjectCosts) GetTotalCharge() (ret SummarizedProjectCostsGetTotalChargeRetType) {
	ret, _ = o.GetTotalChargeOk()
	return ret
}

// GetTotalChargeOk returns a tuple with the TotalCharge field value
// and a boolean to check if the value has been set.
func (o *SummarizedProjectCosts) GetTotalChargeOk() (ret SummarizedProjectCostsGetTotalChargeRetType, ok bool) {
	return getSummarizedProjectCostsGetTotalChargeAttributeTypeOk(o.TotalCharge)
}

// SetTotalCharge sets field value
func (o *SummarizedProjectCosts) SetTotalCharge(v SummarizedProjectCostsGetTotalChargeRetType) {
	setSummarizedProjectCostsGetTotalChargeAttributeType(&o.TotalCharge, v)
}

// GetTotalDiscount returns the TotalDiscount field value
func (o *SummarizedProjectCosts) GetTotalDiscount() (ret SummarizedProjectCostsGetTotalDiscountRetType) {
	ret, _ = o.GetTotalDiscountOk()
	return ret
}

// GetTotalDiscountOk returns a tuple with the TotalDiscount field value
// and a boolean to check if the value has been set.
func (o *SummarizedProjectCosts) GetTotalDiscountOk() (ret SummarizedProjectCostsGetTotalDiscountRetType, ok bool) {
	return getSummarizedProjectCostsGetTotalDiscountAttributeTypeOk(o.TotalDiscount)
}

// SetTotalDiscount sets field value
func (o *SummarizedProjectCosts) SetTotalDiscount(v SummarizedProjectCostsGetTotalDiscountRetType) {
	setSummarizedProjectCostsGetTotalDiscountAttributeType(&o.TotalDiscount, v)
}

func (o SummarizedProjectCosts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getSummarizedProjectCostsGetCustomerAccountIdAttributeTypeOk(o.CustomerAccountId); ok {
		toSerialize["CustomerAccountId"] = val
	}
	if val, ok := getSummarizedProjectCostsGetProjectIdAttributeTypeOk(o.ProjectId); ok {
		toSerialize["ProjectId"] = val
	}
	if val, ok := getSummarizedProjectCostsGetProjectNameAttributeTypeOk(o.ProjectName); ok {
		toSerialize["ProjectName"] = val
	}
	if val, ok := getSummarizedProjectCostsGetTotalChargeAttributeTypeOk(o.TotalCharge); ok {
		toSerialize["TotalCharge"] = val
	}
	if val, ok := getSummarizedProjectCostsGetTotalDiscountAttributeTypeOk(o.TotalDiscount); ok {
		toSerialize["TotalDiscount"] = val
	}
	return toSerialize, nil
}

type NullableSummarizedProjectCosts struct {
	value *SummarizedProjectCosts
	isSet bool
}

func (v NullableSummarizedProjectCosts) Get() *SummarizedProjectCosts {
	return v.value
}

func (v *NullableSummarizedProjectCosts) Set(val *SummarizedProjectCosts) {
	v.value = val
	v.isSet = true
}

func (v NullableSummarizedProjectCosts) IsSet() bool {
	return v.isSet
}

func (v *NullableSummarizedProjectCosts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummarizedProjectCosts(val *SummarizedProjectCosts) *NullableSummarizedProjectCosts {
	return &NullableSummarizedProjectCosts{value: val, isSet: true}
}

func (v NullableSummarizedProjectCosts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummarizedProjectCosts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
