/*
STACKIT Edge Cloud API

This API provides endpoints for managing STACKIT Edge Cloud instances.

API version: 1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1beta1api

import (
	"context"
	"net/http"
)

// assert the implementation matches the interface
var _ DefaultAPI = &DefaultAPIServiceMock{}

// DefaultAPIServiceMock is meant to be used for testing only as a replacement for DefaultAPIService.
// By default all FooExecute() implementations are a no-op. Behavior of the mock can be customized by populating the callbacks in this struct.
type DefaultAPIServiceMock struct {
	// CreateInstanceExecuteMock can be populated to implement the behavior of the CreateInstanceExecute function of this mock
	CreateInstanceExecuteMock *func(r ApiCreateInstanceRequest) (*Instance, *http.Response, error)
	// DeleteInstanceExecuteMock can be populated to implement the behavior of the DeleteInstanceExecute function of this mock
	DeleteInstanceExecuteMock *func(r ApiDeleteInstanceRequest) (*http.Response, error)
	// DeleteInstanceByNameExecuteMock can be populated to implement the behavior of the DeleteInstanceByNameExecute function of this mock
	DeleteInstanceByNameExecuteMock *func(r ApiDeleteInstanceByNameRequest) (*http.Response, error)
	// GetInstanceExecuteMock can be populated to implement the behavior of the GetInstanceExecute function of this mock
	GetInstanceExecuteMock *func(r ApiGetInstanceRequest) (*Instance, *http.Response, error)
	// GetInstanceByNameExecuteMock can be populated to implement the behavior of the GetInstanceByNameExecute function of this mock
	GetInstanceByNameExecuteMock *func(r ApiGetInstanceByNameRequest) (*Instance, *http.Response, error)
	// GetKubeconfigByInstanceIdExecuteMock can be populated to implement the behavior of the GetKubeconfigByInstanceIdExecute function of this mock
	GetKubeconfigByInstanceIdExecuteMock *func(r ApiGetKubeconfigByInstanceIdRequest) (*Kubeconfig, *http.Response, error)
	// GetKubeconfigByInstanceNameExecuteMock can be populated to implement the behavior of the GetKubeconfigByInstanceNameExecute function of this mock
	GetKubeconfigByInstanceNameExecuteMock *func(r ApiGetKubeconfigByInstanceNameRequest) (*Kubeconfig, *http.Response, error)
	// GetTokenByInstanceIdExecuteMock can be populated to implement the behavior of the GetTokenByInstanceIdExecute function of this mock
	GetTokenByInstanceIdExecuteMock *func(r ApiGetTokenByInstanceIdRequest) (*Token, *http.Response, error)
	// GetTokenByInstanceNameExecuteMock can be populated to implement the behavior of the GetTokenByInstanceNameExecute function of this mock
	GetTokenByInstanceNameExecuteMock *func(r ApiGetTokenByInstanceNameRequest) (*Token, *http.Response, error)
	// ListInstancesExecuteMock can be populated to implement the behavior of the ListInstancesExecute function of this mock
	ListInstancesExecuteMock *func(r ApiListInstancesRequest) (*InstanceList, *http.Response, error)
	// Deprecated: ListPlansGlobalExecuteMock can be populated to implement the behavior of the ListPlansGlobalExecute function of this mock
	ListPlansGlobalExecuteMock *func(r ApiListPlansGlobalRequest) (*PlanList, *http.Response, error)
	// ListPlansProjectExecuteMock can be populated to implement the behavior of the ListPlansProjectExecute function of this mock
	ListPlansProjectExecuteMock *func(r ApiListPlansProjectRequest) (*PlanList, *http.Response, error)
	// UpdateInstanceExecuteMock can be populated to implement the behavior of the UpdateInstanceExecute function of this mock
	UpdateInstanceExecuteMock *func(r ApiUpdateInstanceRequest) (*http.Response, error)
	// UpdateInstanceByNameExecuteMock can be populated to implement the behavior of the UpdateInstanceByNameExecute function of this mock
	UpdateInstanceByNameExecuteMock *func(r ApiUpdateInstanceByNameRequest) (*http.Response, error)
}

func (a DefaultAPIServiceMock) CreateInstance(ctx context.Context, projectId string, regionId string) ApiCreateInstanceRequest {
	return ApiCreateInstanceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
	}
}

// CreateInstanceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the CreateInstanceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) CreateInstanceExecute(r ApiCreateInstanceRequest) (*Instance, *http.Response, error) {
	if a.CreateInstanceExecuteMock == nil {
		var localVarReturnValue *Instance
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.CreateInstanceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DeleteInstance(ctx context.Context, projectId string, regionId string, instanceId string) ApiDeleteInstanceRequest {
	return ApiDeleteInstanceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
		instanceId: instanceId,
	}
}

// DeleteInstanceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteInstanceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteInstanceExecute(r ApiDeleteInstanceRequest) (*http.Response, error) {
	if a.DeleteInstanceExecuteMock == nil {
		return &http.Response{}, nil
	}

	return (*a.DeleteInstanceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DeleteInstanceByName(ctx context.Context, projectId string, regionId string, displayName string) ApiDeleteInstanceByNameRequest {
	return ApiDeleteInstanceByNameRequest{
		ApiService:  a,
		ctx:         ctx,
		projectId:   projectId,
		regionId:    regionId,
		displayName: displayName,
	}
}

// DeleteInstanceByNameExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteInstanceByNameExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteInstanceByNameExecute(r ApiDeleteInstanceByNameRequest) (*http.Response, error) {
	if a.DeleteInstanceByNameExecuteMock == nil {
		return &http.Response{}, nil
	}

	return (*a.DeleteInstanceByNameExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetInstance(ctx context.Context, projectId string, regionId string, instanceId string) ApiGetInstanceRequest {
	return ApiGetInstanceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
		instanceId: instanceId,
	}
}

// GetInstanceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetInstanceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetInstanceExecute(r ApiGetInstanceRequest) (*Instance, *http.Response, error) {
	if a.GetInstanceExecuteMock == nil {
		var localVarReturnValue *Instance
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetInstanceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetInstanceByName(ctx context.Context, projectId string, regionId string, displayName string) ApiGetInstanceByNameRequest {
	return ApiGetInstanceByNameRequest{
		ApiService:  a,
		ctx:         ctx,
		projectId:   projectId,
		regionId:    regionId,
		displayName: displayName,
	}
}

// GetInstanceByNameExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetInstanceByNameExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetInstanceByNameExecute(r ApiGetInstanceByNameRequest) (*Instance, *http.Response, error) {
	if a.GetInstanceByNameExecuteMock == nil {
		var localVarReturnValue *Instance
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetInstanceByNameExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetKubeconfigByInstanceId(ctx context.Context, projectId string, regionId string, instanceId string) ApiGetKubeconfigByInstanceIdRequest {
	return ApiGetKubeconfigByInstanceIdRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
		instanceId: instanceId,
	}
}

// GetKubeconfigByInstanceIdExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetKubeconfigByInstanceIdExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetKubeconfigByInstanceIdExecute(r ApiGetKubeconfigByInstanceIdRequest) (*Kubeconfig, *http.Response, error) {
	if a.GetKubeconfigByInstanceIdExecuteMock == nil {
		var localVarReturnValue *Kubeconfig
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetKubeconfigByInstanceIdExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetKubeconfigByInstanceName(ctx context.Context, projectId string, regionId string, displayName string) ApiGetKubeconfigByInstanceNameRequest {
	return ApiGetKubeconfigByInstanceNameRequest{
		ApiService:  a,
		ctx:         ctx,
		projectId:   projectId,
		regionId:    regionId,
		displayName: displayName,
	}
}

// GetKubeconfigByInstanceNameExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetKubeconfigByInstanceNameExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetKubeconfigByInstanceNameExecute(r ApiGetKubeconfigByInstanceNameRequest) (*Kubeconfig, *http.Response, error) {
	if a.GetKubeconfigByInstanceNameExecuteMock == nil {
		var localVarReturnValue *Kubeconfig
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetKubeconfigByInstanceNameExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetTokenByInstanceId(ctx context.Context, projectId string, regionId string, instanceId string) ApiGetTokenByInstanceIdRequest {
	return ApiGetTokenByInstanceIdRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
		instanceId: instanceId,
	}
}

// GetTokenByInstanceIdExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetTokenByInstanceIdExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetTokenByInstanceIdExecute(r ApiGetTokenByInstanceIdRequest) (*Token, *http.Response, error) {
	if a.GetTokenByInstanceIdExecuteMock == nil {
		var localVarReturnValue *Token
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetTokenByInstanceIdExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetTokenByInstanceName(ctx context.Context, projectId string, regionId string, displayName string) ApiGetTokenByInstanceNameRequest {
	return ApiGetTokenByInstanceNameRequest{
		ApiService:  a,
		ctx:         ctx,
		projectId:   projectId,
		regionId:    regionId,
		displayName: displayName,
	}
}

// GetTokenByInstanceNameExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetTokenByInstanceNameExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetTokenByInstanceNameExecute(r ApiGetTokenByInstanceNameRequest) (*Token, *http.Response, error) {
	if a.GetTokenByInstanceNameExecuteMock == nil {
		var localVarReturnValue *Token
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.GetTokenByInstanceNameExecuteMock)(r)
}

func (a DefaultAPIServiceMock) ListInstances(ctx context.Context, projectId string, regionId string) ApiListInstancesRequest {
	return ApiListInstancesRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
	}
}

// ListInstancesExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListInstancesExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListInstancesExecute(r ApiListInstancesRequest) (*InstanceList, *http.Response, error) {
	if a.ListInstancesExecuteMock == nil {
		var localVarReturnValue *InstanceList
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.ListInstancesExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) ListPlansGlobal(ctx context.Context) ApiListPlansGlobalRequest {
	return ApiListPlansGlobalRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Deprecated: ListPlansGlobalExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListPlansGlobalExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListPlansGlobalExecute(r ApiListPlansGlobalRequest) (*PlanList, *http.Response, error) {
	if a.ListPlansGlobalExecuteMock == nil {
		var localVarReturnValue *PlanList
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.ListPlansGlobalExecuteMock)(r)
}

func (a DefaultAPIServiceMock) ListPlansProject(ctx context.Context, projectId string) ApiListPlansProjectRequest {
	return ApiListPlansProjectRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// ListPlansProjectExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListPlansProjectExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListPlansProjectExecute(r ApiListPlansProjectRequest) (*PlanList, *http.Response, error) {
	if a.ListPlansProjectExecuteMock == nil {
		var localVarReturnValue *PlanList
		return localVarReturnValue, &http.Response{}, nil
	}

	return (*a.ListPlansProjectExecuteMock)(r)
}

func (a DefaultAPIServiceMock) UpdateInstance(ctx context.Context, projectId string, regionId string, instanceId string) ApiUpdateInstanceRequest {
	return ApiUpdateInstanceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		regionId:   regionId,
		instanceId: instanceId,
	}
}

// UpdateInstanceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the UpdateInstanceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) UpdateInstanceExecute(r ApiUpdateInstanceRequest) (*http.Response, error) {
	if a.UpdateInstanceExecuteMock == nil {
		return &http.Response{}, nil
	}

	return (*a.UpdateInstanceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) UpdateInstanceByName(ctx context.Context, projectId string, regionId string, displayName string) ApiUpdateInstanceByNameRequest {
	return ApiUpdateInstanceByNameRequest{
		ApiService:  a,
		ctx:         ctx,
		projectId:   projectId,
		regionId:    regionId,
		displayName: displayName,
	}
}

// UpdateInstanceByNameExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the UpdateInstanceByNameExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) UpdateInstanceByNameExecute(r ApiUpdateInstanceByNameRequest) (*http.Response, error) {
	if a.UpdateInstanceByNameExecuteMock == nil {
		return &http.Response{}, nil
	}

	return (*a.UpdateInstanceByNameExecuteMock)(r)
}
