/*
STACKIT MongoDB Service API

This is the documentation for the STACKIT MongoDB Flex Service API

API version: 2.0.0
Contact: support@stackit.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2api

import (
	"encoding/json"
	"fmt"
)

// ListAdvisorSlowQueriesRegionParameter the model 'ListAdvisorSlowQueriesRegionParameter'
type ListAdvisorSlowQueriesRegionParameter string

// List of ListAdvisorSlowQueries_region_parameter
const (
	LISTADVISORSLOWQUERIESREGIONPARAMETER_EU01                     ListAdvisorSlowQueriesRegionParameter = "eu01"
	LISTADVISORSLOWQUERIESREGIONPARAMETER_EU02                     ListAdvisorSlowQueriesRegionParameter = "eu02"
	LISTADVISORSLOWQUERIESREGIONPARAMETER_UNKNOWN_DEFAULT_OPEN_API ListAdvisorSlowQueriesRegionParameter = "unknown_default_open_api"
)

// All allowed values of ListAdvisorSlowQueriesRegionParameter enum
var AllowedListAdvisorSlowQueriesRegionParameterEnumValues = []ListAdvisorSlowQueriesRegionParameter{
	"eu01",
	"eu02",
	"unknown_default_open_api",
}

func (v *ListAdvisorSlowQueriesRegionParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ListAdvisorSlowQueriesRegionParameter(value)
	for _, existing := range AllowedListAdvisorSlowQueriesRegionParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = LISTADVISORSLOWQUERIESREGIONPARAMETER_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewListAdvisorSlowQueriesRegionParameterFromValue returns a pointer to a valid ListAdvisorSlowQueriesRegionParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewListAdvisorSlowQueriesRegionParameterFromValue(v string) (*ListAdvisorSlowQueriesRegionParameter, error) {
	ev := ListAdvisorSlowQueriesRegionParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ListAdvisorSlowQueriesRegionParameter: valid values are %v", v, AllowedListAdvisorSlowQueriesRegionParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ListAdvisorSlowQueriesRegionParameter) IsValid() bool {
	for _, existing := range AllowedListAdvisorSlowQueriesRegionParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ListAdvisorSlowQueries_region_parameter value
func (v ListAdvisorSlowQueriesRegionParameter) Ptr() *ListAdvisorSlowQueriesRegionParameter {
	return &v
}

type NullableListAdvisorSlowQueriesRegionParameter struct {
	value *ListAdvisorSlowQueriesRegionParameter
	isSet bool
}

func (v NullableListAdvisorSlowQueriesRegionParameter) Get() *ListAdvisorSlowQueriesRegionParameter {
	return v.value
}

func (v *NullableListAdvisorSlowQueriesRegionParameter) Set(val *ListAdvisorSlowQueriesRegionParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableListAdvisorSlowQueriesRegionParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableListAdvisorSlowQueriesRegionParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAdvisorSlowQueriesRegionParameter(val *ListAdvisorSlowQueriesRegionParameter) *NullableListAdvisorSlowQueriesRegionParameter {
	return &NullableListAdvisorSlowQueriesRegionParameter{value: val, isSet: true}
}

func (v NullableListAdvisorSlowQueriesRegionParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAdvisorSlowQueriesRegionParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
