/*
STACKIT MongoDB Service API

This is the documentation for the STACKIT MongoDB Flex Service API

API version: 2.0.0
Contact: support@stackit.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2api

import (
	"encoding/json"
	"fmt"
)

// ListSuggestedIndexesRegionParameter the model 'ListSuggestedIndexesRegionParameter'
type ListSuggestedIndexesRegionParameter string

// List of ListSuggestedIndexes_region_parameter
const (
	LISTSUGGESTEDINDEXESREGIONPARAMETER_EU01                     ListSuggestedIndexesRegionParameter = "eu01"
	LISTSUGGESTEDINDEXESREGIONPARAMETER_EU02                     ListSuggestedIndexesRegionParameter = "eu02"
	LISTSUGGESTEDINDEXESREGIONPARAMETER_UNKNOWN_DEFAULT_OPEN_API ListSuggestedIndexesRegionParameter = "unknown_default_open_api"
)

// All allowed values of ListSuggestedIndexesRegionParameter enum
var AllowedListSuggestedIndexesRegionParameterEnumValues = []ListSuggestedIndexesRegionParameter{
	"eu01",
	"eu02",
	"unknown_default_open_api",
}

func (v *ListSuggestedIndexesRegionParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ListSuggestedIndexesRegionParameter(value)
	for _, existing := range AllowedListSuggestedIndexesRegionParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = LISTSUGGESTEDINDEXESREGIONPARAMETER_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewListSuggestedIndexesRegionParameterFromValue returns a pointer to a valid ListSuggestedIndexesRegionParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewListSuggestedIndexesRegionParameterFromValue(v string) (*ListSuggestedIndexesRegionParameter, error) {
	ev := ListSuggestedIndexesRegionParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ListSuggestedIndexesRegionParameter: valid values are %v", v, AllowedListSuggestedIndexesRegionParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ListSuggestedIndexesRegionParameter) IsValid() bool {
	for _, existing := range AllowedListSuggestedIndexesRegionParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ListSuggestedIndexes_region_parameter value
func (v ListSuggestedIndexesRegionParameter) Ptr() *ListSuggestedIndexesRegionParameter {
	return &v
}

type NullableListSuggestedIndexesRegionParameter struct {
	value *ListSuggestedIndexesRegionParameter
	isSet bool
}

func (v NullableListSuggestedIndexesRegionParameter) Get() *ListSuggestedIndexesRegionParameter {
	return v.value
}

func (v *NullableListSuggestedIndexesRegionParameter) Set(val *ListSuggestedIndexesRegionParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableListSuggestedIndexesRegionParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableListSuggestedIndexesRegionParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSuggestedIndexesRegionParameter(val *ListSuggestedIndexesRegionParameter) *NullableListSuggestedIndexesRegionParameter {
	return &NullableListSuggestedIndexesRegionParameter{value: val, isSet: true}
}

func (v NullableListSuggestedIndexesRegionParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSuggestedIndexesRegionParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
