/*
STACKIT MSSQL Service API

This is the documentation for the STACKIT MSSQL service

API version: 3beta1
Contact: support@stackit.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3beta1api

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateInstanceRequestPayloadNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInstanceRequestPayloadNetwork{}

// UpdateInstanceRequestPayloadNetwork the network configuration of the instance.
type UpdateInstanceRequestPayloadNetwork struct {
	// List of IPV4 cidr.
	Acl                  []string `json:"acl"`
	AdditionalProperties map[string]interface{}
}

type _UpdateInstanceRequestPayloadNetwork UpdateInstanceRequestPayloadNetwork

// NewUpdateInstanceRequestPayloadNetwork instantiates a new UpdateInstanceRequestPayloadNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInstanceRequestPayloadNetwork(acl []string) *UpdateInstanceRequestPayloadNetwork {
	this := UpdateInstanceRequestPayloadNetwork{}
	this.Acl = acl
	return &this
}

// NewUpdateInstanceRequestPayloadNetworkWithDefaults instantiates a new UpdateInstanceRequestPayloadNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInstanceRequestPayloadNetworkWithDefaults() *UpdateInstanceRequestPayloadNetwork {
	this := UpdateInstanceRequestPayloadNetwork{}
	return &this
}

// GetAcl returns the Acl field value
func (o *UpdateInstanceRequestPayloadNetwork) GetAcl() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Acl
}

// GetAclOk returns a tuple with the Acl field value
// and a boolean to check if the value has been set.
func (o *UpdateInstanceRequestPayloadNetwork) GetAclOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Acl, true
}

// SetAcl sets field value
func (o *UpdateInstanceRequestPayloadNetwork) SetAcl(v []string) {
	o.Acl = v
}

func (o UpdateInstanceRequestPayloadNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInstanceRequestPayloadNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["acl"] = o.Acl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateInstanceRequestPayloadNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"acl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateInstanceRequestPayloadNetwork := _UpdateInstanceRequestPayloadNetwork{}

	err = json.Unmarshal(data, &varUpdateInstanceRequestPayloadNetwork)

	if err != nil {
		return err
	}

	*o = UpdateInstanceRequestPayloadNetwork(varUpdateInstanceRequestPayloadNetwork)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "acl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateInstanceRequestPayloadNetwork struct {
	value *UpdateInstanceRequestPayloadNetwork
	isSet bool
}

func (v NullableUpdateInstanceRequestPayloadNetwork) Get() *UpdateInstanceRequestPayloadNetwork {
	return v.value
}

func (v *NullableUpdateInstanceRequestPayloadNetwork) Set(val *UpdateInstanceRequestPayloadNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInstanceRequestPayloadNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInstanceRequestPayloadNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInstanceRequestPayloadNetwork(val *UpdateInstanceRequestPayloadNetwork) *NullableUpdateInstanceRequestPayloadNetwork {
	return &NullableUpdateInstanceRequestPayloadNetwork{value: val, isSet: true}
}

func (v NullableUpdateInstanceRequestPayloadNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInstanceRequestPayloadNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
