/*
CDN API

API used to create and manage your CDN distributions.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cdn

import (
	"encoding/json"
)

// checks if the WafStatusRuleBlockReasonInheritedFromCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WafStatusRuleBlockReasonInheritedFromCollection{}

/*
	types and functions for collectionId
*/

// isNotNullableString
type WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType = *string

func getWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeTypeOk(arg WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType) (ret WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType(arg *WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType, val WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType) {
	*arg = &val
}

type WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdArgType = string
type WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType = string

/*
	types and functions for type
*/

// isNotNullableString
type WafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType = *string

func getWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeTypeOk(arg WafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType) (ret WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType(arg *WafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType, val WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType) {
	*arg = &val
}

type WafStatusRuleBlockReasonInheritedFromCollectionGetTypeArgType = string
type WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType = string

// WafStatusRuleBlockReasonInheritedFromCollection struct for WafStatusRuleBlockReasonInheritedFromCollection
type WafStatusRuleBlockReasonInheritedFromCollection struct {
	// The Collection that caused this rule to be in its current state.
	// REQUIRED
	CollectionId WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType `json:"collectionId" required:"true"`
	// This is always `inheritedFromCollection`
	// REQUIRED
	Type WafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType `json:"type" required:"true"`
}

type _WafStatusRuleBlockReasonInheritedFromCollection WafStatusRuleBlockReasonInheritedFromCollection

// NewWafStatusRuleBlockReasonInheritedFromCollection instantiates a new WafStatusRuleBlockReasonInheritedFromCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWafStatusRuleBlockReasonInheritedFromCollection(collectionId WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdArgType, types WafStatusRuleBlockReasonInheritedFromCollectionGetTypeArgType) *WafStatusRuleBlockReasonInheritedFromCollection {
	this := WafStatusRuleBlockReasonInheritedFromCollection{}
	setWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType(&this.CollectionId, collectionId)
	setWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType(&this.Type, types)
	return &this
}

// NewWafStatusRuleBlockReasonInheritedFromCollectionWithDefaults instantiates a new WafStatusRuleBlockReasonInheritedFromCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWafStatusRuleBlockReasonInheritedFromCollectionWithDefaults() *WafStatusRuleBlockReasonInheritedFromCollection {
	this := WafStatusRuleBlockReasonInheritedFromCollection{}
	return &this
}

// GetCollectionId returns the CollectionId field value
func (o *WafStatusRuleBlockReasonInheritedFromCollection) GetCollectionId() (ret WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType) {
	ret, _ = o.GetCollectionIdOk()
	return ret
}

// GetCollectionIdOk returns a tuple with the CollectionId field value
// and a boolean to check if the value has been set.
func (o *WafStatusRuleBlockReasonInheritedFromCollection) GetCollectionIdOk() (ret WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType, ok bool) {
	return getWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeTypeOk(o.CollectionId)
}

// SetCollectionId sets field value
func (o *WafStatusRuleBlockReasonInheritedFromCollection) SetCollectionId(v WafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdRetType) {
	setWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeType(&o.CollectionId, v)
}

// GetType returns the Type field value
func (o *WafStatusRuleBlockReasonInheritedFromCollection) GetType() (ret WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType) {
	ret, _ = o.GetTypeOk()
	return ret
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WafStatusRuleBlockReasonInheritedFromCollection) GetTypeOk() (ret WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType, ok bool) {
	return getWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeTypeOk(o.Type)
}

// SetType sets field value
func (o *WafStatusRuleBlockReasonInheritedFromCollection) SetType(v WafStatusRuleBlockReasonInheritedFromCollectionGetTypeRetType) {
	setWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeType(&o.Type, v)
}

func (o WafStatusRuleBlockReasonInheritedFromCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getWafStatusRuleBlockReasonInheritedFromCollectionGetCollectionIdAttributeTypeOk(o.CollectionId); ok {
		toSerialize["CollectionId"] = val
	}
	if val, ok := getWafStatusRuleBlockReasonInheritedFromCollectionGetTypeAttributeTypeOk(o.Type); ok {
		toSerialize["Type"] = val
	}
	return toSerialize, nil
}

type NullableWafStatusRuleBlockReasonInheritedFromCollection struct {
	value *WafStatusRuleBlockReasonInheritedFromCollection
	isSet bool
}

func (v NullableWafStatusRuleBlockReasonInheritedFromCollection) Get() *WafStatusRuleBlockReasonInheritedFromCollection {
	return v.value
}

func (v *NullableWafStatusRuleBlockReasonInheritedFromCollection) Set(val *WafStatusRuleBlockReasonInheritedFromCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableWafStatusRuleBlockReasonInheritedFromCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableWafStatusRuleBlockReasonInheritedFromCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafStatusRuleBlockReasonInheritedFromCollection(val *WafStatusRuleBlockReasonInheritedFromCollection) *NullableWafStatusRuleBlockReasonInheritedFromCollection {
	return &NullableWafStatusRuleBlockReasonInheritedFromCollection{value: val, isSet: true}
}

func (v NullableWafStatusRuleBlockReasonInheritedFromCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafStatusRuleBlockReasonInheritedFromCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
