/*
CDN API

API used to create and manage your CDN distributions.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
package cdn

import (
	"encoding/json"
)

// checks if the BucketBackend type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BucketBackend{}

/*
	types and functions for bucketUrl
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetBucketUrlAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getBucketBackendGetBucketUrlAttributeTypeOk(arg BucketBackendGetBucketUrlAttributeType) (ret BucketBackendGetBucketUrlRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setBucketBackendGetBucketUrlAttributeType(arg *BucketBackendGetBucketUrlAttributeType, val BucketBackendGetBucketUrlRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetBucketUrlArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetBucketUrlRetType = string

/*
	types and functions for region
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetRegionAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getBucketBackendGetRegionAttributeTypeOk(arg BucketBackendGetRegionAttributeType) (ret BucketBackendGetRegionRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setBucketBackendGetRegionAttributeType(arg *BucketBackendGetRegionAttributeType, val BucketBackendGetRegionRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetRegionArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetRegionRetType = string

/*
	types and functions for type
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetTypeAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getBucketBackendGetTypeAttributeTypeOk(arg BucketBackendGetTypeAttributeType) (ret BucketBackendGetTypeRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setBucketBackendGetTypeAttributeType(arg *BucketBackendGetTypeAttributeType, val BucketBackendGetTypeRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetTypeArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackendGetTypeRetType = string

// BucketBackend struct for BucketBackend
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type BucketBackend struct {
	// REQUIRED
	BucketUrl BucketBackendGetBucketUrlAttributeType `json:"bucketUrl" required:"true"`
	// REQUIRED
	Region BucketBackendGetRegionAttributeType `json:"region" required:"true"`
	// REQUIRED
	Type BucketBackendGetTypeAttributeType `json:"type" required:"true"`
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type _BucketBackend BucketBackend

// NewBucketBackend instantiates a new BucketBackend object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewBucketBackend(bucketUrl BucketBackendGetBucketUrlArgType, region BucketBackendGetRegionArgType, types BucketBackendGetTypeArgType) *BucketBackend {
	this := BucketBackend{}
	setBucketBackendGetBucketUrlAttributeType(&this.BucketUrl, bucketUrl)
	setBucketBackendGetRegionAttributeType(&this.Region, region)
	setBucketBackendGetTypeAttributeType(&this.Type, types)
	return &this
}

// NewBucketBackendWithDefaults instantiates a new BucketBackend object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewBucketBackendWithDefaults() *BucketBackend {
	this := BucketBackend{}
	return &this
}

// GetBucketUrl returns the BucketUrl field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetBucketUrl() (ret BucketBackendGetBucketUrlRetType) {
	ret, _ = o.GetBucketUrlOk()
	return ret
}

// GetBucketUrlOk returns a tuple with the BucketUrl field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetBucketUrlOk() (ret BucketBackendGetBucketUrlRetType, ok bool) {
	return getBucketBackendGetBucketUrlAttributeTypeOk(o.BucketUrl)
}

// SetBucketUrl sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) SetBucketUrl(v BucketBackendGetBucketUrlRetType) {
	setBucketBackendGetBucketUrlAttributeType(&o.BucketUrl, v)
}

// GetRegion returns the Region field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetRegion() (ret BucketBackendGetRegionRetType) {
	ret, _ = o.GetRegionOk()
	return ret
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetRegionOk() (ret BucketBackendGetRegionRetType, ok bool) {
	return getBucketBackendGetRegionAttributeTypeOk(o.Region)
}

// SetRegion sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) SetRegion(v BucketBackendGetRegionRetType) {
	setBucketBackendGetRegionAttributeType(&o.Region, v)
}

// GetType returns the Type field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetType() (ret BucketBackendGetTypeRetType) {
	ret, _ = o.GetTypeOk()
	return ret
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) GetTypeOk() (ret BucketBackendGetTypeRetType, ok bool) {
	return getBucketBackendGetTypeAttributeTypeOk(o.Type)
}

// SetType sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *BucketBackend) SetType(v BucketBackendGetTypeRetType) {
	setBucketBackendGetTypeAttributeType(&o.Type, v)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o BucketBackend) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getBucketBackendGetBucketUrlAttributeTypeOk(o.BucketUrl); ok {
		toSerialize["BucketUrl"] = val
	}
	if val, ok := getBucketBackendGetRegionAttributeTypeOk(o.Region); ok {
		toSerialize["Region"] = val
	}
	if val, ok := getBucketBackendGetTypeAttributeTypeOk(o.Type); ok {
		toSerialize["Type"] = val
	}
	return toSerialize, nil
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type NullableBucketBackend struct {
	value *BucketBackend
	isSet bool
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableBucketBackend) Get() *BucketBackend {
	return v.value
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableBucketBackend) Set(val *BucketBackend) {
	v.value = val
	v.isSet = true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableBucketBackend) IsSet() bool {
	return v.isSet
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableBucketBackend) Unset() {
	v.value = nil
	v.isSet = false
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewNullableBucketBackend(val *BucketBackend) *NullableBucketBackend {
	return &NullableBucketBackend{value: val, isSet: true}
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableBucketBackend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableBucketBackend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
