/*
STACKIT Object Storage API

STACKIT API to manage the Object Storage

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package objectstorage

import (
	"encoding/json"
)

// checks if the CreateBucketResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBucketResponse{}

/*
	types and functions for bucket
*/

// isNotNullableString
type CreateBucketResponseGetBucketAttributeType = *string

func getCreateBucketResponseGetBucketAttributeTypeOk(arg CreateBucketResponseGetBucketAttributeType) (ret CreateBucketResponseGetBucketRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateBucketResponseGetBucketAttributeType(arg *CreateBucketResponseGetBucketAttributeType, val CreateBucketResponseGetBucketRetType) {
	*arg = &val
}

type CreateBucketResponseGetBucketArgType = string
type CreateBucketResponseGetBucketRetType = string

/*
	types and functions for project
*/

// isNotNullableString
type CreateBucketResponseGetProjectAttributeType = *string

func getCreateBucketResponseGetProjectAttributeTypeOk(arg CreateBucketResponseGetProjectAttributeType) (ret CreateBucketResponseGetProjectRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setCreateBucketResponseGetProjectAttributeType(arg *CreateBucketResponseGetProjectAttributeType, val CreateBucketResponseGetProjectRetType) {
	*arg = &val
}

type CreateBucketResponseGetProjectArgType = string
type CreateBucketResponseGetProjectRetType = string

// CreateBucketResponse struct for CreateBucketResponse
type CreateBucketResponse struct {
	// Name of the bucket
	// REQUIRED
	Bucket CreateBucketResponseGetBucketAttributeType `json:"bucket"`
	// Project ID
	// REQUIRED
	Project CreateBucketResponseGetProjectAttributeType `json:"project"`
}

type _CreateBucketResponse CreateBucketResponse

// NewCreateBucketResponse instantiates a new CreateBucketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBucketResponse(bucket CreateBucketResponseGetBucketArgType, project CreateBucketResponseGetProjectArgType) *CreateBucketResponse {
	this := CreateBucketResponse{}
	setCreateBucketResponseGetBucketAttributeType(&this.Bucket, bucket)
	setCreateBucketResponseGetProjectAttributeType(&this.Project, project)
	return &this
}

// NewCreateBucketResponseWithDefaults instantiates a new CreateBucketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBucketResponseWithDefaults() *CreateBucketResponse {
	this := CreateBucketResponse{}
	return &this
}

// GetBucket returns the Bucket field value
func (o *CreateBucketResponse) GetBucket() (ret CreateBucketResponseGetBucketRetType) {
	ret, _ = o.GetBucketOk()
	return ret
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *CreateBucketResponse) GetBucketOk() (ret CreateBucketResponseGetBucketRetType, ok bool) {
	return getCreateBucketResponseGetBucketAttributeTypeOk(o.Bucket)
}

// SetBucket sets field value
func (o *CreateBucketResponse) SetBucket(v CreateBucketResponseGetBucketRetType) {
	setCreateBucketResponseGetBucketAttributeType(&o.Bucket, v)
}

// GetProject returns the Project field value
func (o *CreateBucketResponse) GetProject() (ret CreateBucketResponseGetProjectRetType) {
	ret, _ = o.GetProjectOk()
	return ret
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *CreateBucketResponse) GetProjectOk() (ret CreateBucketResponseGetProjectRetType, ok bool) {
	return getCreateBucketResponseGetProjectAttributeTypeOk(o.Project)
}

// SetProject sets field value
func (o *CreateBucketResponse) SetProject(v CreateBucketResponseGetProjectRetType) {
	setCreateBucketResponseGetProjectAttributeType(&o.Project, v)
}

func (o CreateBucketResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getCreateBucketResponseGetBucketAttributeTypeOk(o.Bucket); ok {
		toSerialize["Bucket"] = val
	}
	if val, ok := getCreateBucketResponseGetProjectAttributeTypeOk(o.Project); ok {
		toSerialize["Project"] = val
	}
	return toSerialize, nil
}

type NullableCreateBucketResponse struct {
	value *CreateBucketResponse
	isSet bool
}

func (v NullableCreateBucketResponse) Get() *CreateBucketResponse {
	return v.value
}

func (v *NullableCreateBucketResponse) Set(val *CreateBucketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBucketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBucketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBucketResponse(val *CreateBucketResponse) *NullableCreateBucketResponse {
	return &NullableCreateBucketResponse{value: val, isSet: true}
}

func (v NullableCreateBucketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBucketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
