/*
STACKIT Application Load Balancer Web Application Firewall API

Generate a Web Application Firewall (WAF) to use with Application Load Balancers (ALB). The name of the WAF configuration is used in the listener of the ALB. This will activate the WAF for that ALB. An ALB with a WAF can have Managed Rule Set (MRS) and in addition can have Custom Rule Group (CRG). To create a WAF one first needs to create all the configurations that are referenced in the WAF configuration. Currently this only consists of a rule configuration, which is written in Seclang. Once all configurations are created and referenced in the WAF configuration it can be used with an ALB. Currently updating a WAF configuration will not update an existing ALB until the Load Balancer VMs are restarted.

API version: 1beta.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1betaapi

import (
	"encoding/json"
	"fmt"
)

// MRSType1 Get the managed rule set type.
type MRSType1 string

// List of MRS_Type_1
const (
	MRSTYPE1_TYPE_UNSPECIFIED         MRSType1 = "TYPE_UNSPECIFIED"
	MRSTYPE1_TYPE_OWASP_CRS           MRSType1 = "TYPE_OWASP_CRS"
	MRSTYPE1_UNKNOWN_DEFAULT_OPEN_API MRSType1 = "unknown_default_open_api"
)

// All allowed values of MRSType1 enum
var AllowedMRSType1EnumValues = []MRSType1{
	"TYPE_UNSPECIFIED",
	"TYPE_OWASP_CRS",
	"unknown_default_open_api",
}

func (v *MRSType1) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MRSType1(value)
	for _, existing := range AllowedMRSType1EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = MRSTYPE1_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewMRSType1FromValue returns a pointer to a valid MRSType1
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMRSType1FromValue(v string) (*MRSType1, error) {
	ev := MRSType1(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MRSType1: valid values are %v", v, AllowedMRSType1EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MRSType1) IsValid() bool {
	for _, existing := range AllowedMRSType1EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MRS_Type_1 value
func (v MRSType1) Ptr() *MRSType1 {
	return &v
}

type NullableMRSType1 struct {
	value *MRSType1
	isSet bool
}

func (v NullableMRSType1) Get() *MRSType1 {
	return v.value
}

func (v *NullableMRSType1) Set(val *MRSType1) {
	v.value = val
	v.isSet = true
}

func (v NullableMRSType1) IsSet() bool {
	return v.isSet
}

func (v *NullableMRSType1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMRSType1(val *MRSType1) *NullableMRSType1 {
	return &NullableMRSType1{value: val, isSet: true}
}

func (v NullableMRSType1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMRSType1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
