/*
STACKIT Membership API

The Membership API is used to manage memberships, roles and permissions of STACKIT resources, like projects, folders, organizations and other resources.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorization

type ListSubjectIdsResponse struct {
	Cursor *string `json:"cursor,omitempty"`
	// REQUIRED
	Items *[]string `json:"items"`
	// Can be cast to int32 without loss of precision.
	Limit *int64 `json:"limit,omitempty"`
}
