/*
STACKIT Secrets Manager API

This API provides endpoints for managing the Secrets-Manager.

API version: 1alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alphaapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetInstanceRoleBindingsPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInstanceRoleBindingsPayload{}

// GetInstanceRoleBindingsPayload struct for GetInstanceRoleBindingsPayload
type GetInstanceRoleBindingsPayload struct {
	Role                 string `json:"role" validate:"regexp=^[a-z](?:[-.]?[a-z]){1,63}$"`
	Subject              string `json:"subject"`
	AdditionalProperties map[string]interface{}
}

type _GetInstanceRoleBindingsPayload GetInstanceRoleBindingsPayload

// NewGetInstanceRoleBindingsPayload instantiates a new GetInstanceRoleBindingsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstanceRoleBindingsPayload(role string, subject string) *GetInstanceRoleBindingsPayload {
	this := GetInstanceRoleBindingsPayload{}
	this.Role = role
	this.Subject = subject
	return &this
}

// NewGetInstanceRoleBindingsPayloadWithDefaults instantiates a new GetInstanceRoleBindingsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstanceRoleBindingsPayloadWithDefaults() *GetInstanceRoleBindingsPayload {
	this := GetInstanceRoleBindingsPayload{}
	return &this
}

// GetRole returns the Role field value
func (o *GetInstanceRoleBindingsPayload) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GetInstanceRoleBindingsPayload) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GetInstanceRoleBindingsPayload) SetRole(v string) {
	o.Role = v
}

// GetSubject returns the Subject field value
func (o *GetInstanceRoleBindingsPayload) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *GetInstanceRoleBindingsPayload) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *GetInstanceRoleBindingsPayload) SetSubject(v string) {
	o.Subject = v
}

func (o GetInstanceRoleBindingsPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInstanceRoleBindingsPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["subject"] = o.Subject

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetInstanceRoleBindingsPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"subject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetInstanceRoleBindingsPayload := _GetInstanceRoleBindingsPayload{}

	err = json.Unmarshal(data, &varGetInstanceRoleBindingsPayload)

	if err != nil {
		return err
	}

	*o = GetInstanceRoleBindingsPayload(varGetInstanceRoleBindingsPayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role")
		delete(additionalProperties, "subject")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetInstanceRoleBindingsPayload struct {
	value *GetInstanceRoleBindingsPayload
	isSet bool
}

func (v NullableGetInstanceRoleBindingsPayload) Get() *GetInstanceRoleBindingsPayload {
	return v.value
}

func (v *NullableGetInstanceRoleBindingsPayload) Set(val *GetInstanceRoleBindingsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstanceRoleBindingsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstanceRoleBindingsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstanceRoleBindingsPayload(val *GetInstanceRoleBindingsPayload) *NullableGetInstanceRoleBindingsPayload {
	return &NullableGetInstanceRoleBindingsPayload{value: val, isSet: true}
}

func (v NullableGetInstanceRoleBindingsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstanceRoleBindingsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
