/*
STACKIT Kubernetes Engine API

The SKE API provides endpoints to create, update or delete clusters within STACKIT projects and to trigger further cluster management tasks.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ske

import (
	"encoding/json"
)

// checks if the IDPKubeconfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IDPKubeconfig{}

/*
	types and functions for kubeconfig
*/

// isNotNullableString
type IDPKubeconfigGetKubeconfigAttributeType = *string

func getIDPKubeconfigGetKubeconfigAttributeTypeOk(arg IDPKubeconfigGetKubeconfigAttributeType) (ret IDPKubeconfigGetKubeconfigRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setIDPKubeconfigGetKubeconfigAttributeType(arg *IDPKubeconfigGetKubeconfigAttributeType, val IDPKubeconfigGetKubeconfigRetType) {
	*arg = &val
}

type IDPKubeconfigGetKubeconfigArgType = string
type IDPKubeconfigGetKubeconfigRetType = string

// IDPKubeconfig struct for IDPKubeconfig
type IDPKubeconfig struct {
	Kubeconfig IDPKubeconfigGetKubeconfigAttributeType `json:"kubeconfig,omitempty"`
}

// NewIDPKubeconfig instantiates a new IDPKubeconfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIDPKubeconfig() *IDPKubeconfig {
	this := IDPKubeconfig{}
	return &this
}

// NewIDPKubeconfigWithDefaults instantiates a new IDPKubeconfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIDPKubeconfigWithDefaults() *IDPKubeconfig {
	this := IDPKubeconfig{}
	return &this
}

// GetKubeconfig returns the Kubeconfig field value if set, zero value otherwise.
func (o *IDPKubeconfig) GetKubeconfig() (res IDPKubeconfigGetKubeconfigRetType) {
	res, _ = o.GetKubeconfigOk()
	return
}

// GetKubeconfigOk returns a tuple with the Kubeconfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDPKubeconfig) GetKubeconfigOk() (ret IDPKubeconfigGetKubeconfigRetType, ok bool) {
	return getIDPKubeconfigGetKubeconfigAttributeTypeOk(o.Kubeconfig)
}

// HasKubeconfig returns a boolean if a field has been set.
func (o *IDPKubeconfig) HasKubeconfig() bool {
	_, ok := o.GetKubeconfigOk()
	return ok
}

// SetKubeconfig gets a reference to the given string and assigns it to the Kubeconfig field.
func (o *IDPKubeconfig) SetKubeconfig(v IDPKubeconfigGetKubeconfigRetType) {
	setIDPKubeconfigGetKubeconfigAttributeType(&o.Kubeconfig, v)
}

func (o IDPKubeconfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getIDPKubeconfigGetKubeconfigAttributeTypeOk(o.Kubeconfig); ok {
		toSerialize["Kubeconfig"] = val
	}
	return toSerialize, nil
}

type NullableIDPKubeconfig struct {
	value *IDPKubeconfig
	isSet bool
}

func (v NullableIDPKubeconfig) Get() *IDPKubeconfig {
	return v.value
}

func (v *NullableIDPKubeconfig) Set(val *IDPKubeconfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIDPKubeconfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIDPKubeconfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIDPKubeconfig(val *IDPKubeconfig) *NullableIDPKubeconfig {
	return &NullableIDPKubeconfig{value: val, isSet: true}
}

func (v NullableIDPKubeconfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIDPKubeconfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
