/*
STACKIT Kubernetes Engine API

The SKE API provides endpoints to create, update or delete clusters within STACKIT projects and to trigger further cluster management tasks.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
package ske

import (
	"encoding/json"
)

// checks if the ApplicationLoadBalancer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationLoadBalancer{}

/*
	types and functions for enabled
*/

// isBoolean
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type ApplicationLoadBalancergetEnabledAttributeType = *bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type ApplicationLoadBalancergetEnabledArgType = bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type ApplicationLoadBalancergetEnabledRetType = bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getApplicationLoadBalancergetEnabledAttributeTypeOk(arg ApplicationLoadBalancergetEnabledAttributeType) (ret ApplicationLoadBalancergetEnabledRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setApplicationLoadBalancergetEnabledAttributeType(arg *ApplicationLoadBalancergetEnabledAttributeType, val ApplicationLoadBalancergetEnabledRetType) {
	*arg = &val
}

// ApplicationLoadBalancer struct for ApplicationLoadBalancer
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type ApplicationLoadBalancer struct {
	// Enables the application load balancer extension. ⚠️ Note: This feature is in private preview. Enabling application load balancer extension is only possible for enabled accounts. Otherwise the request will be rejected.
	// REQUIRED
	Enabled ApplicationLoadBalancergetEnabledAttributeType `json:"enabled" required:"true"`
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type _ApplicationLoadBalancer ApplicationLoadBalancer

// NewApplicationLoadBalancer instantiates a new ApplicationLoadBalancer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewApplicationLoadBalancer(enabled ApplicationLoadBalancergetEnabledArgType) *ApplicationLoadBalancer {
	this := ApplicationLoadBalancer{}
	setApplicationLoadBalancergetEnabledAttributeType(&this.Enabled, enabled)
	return &this
}

// NewApplicationLoadBalancerWithDefaults instantiates a new ApplicationLoadBalancer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewApplicationLoadBalancerWithDefaults() *ApplicationLoadBalancer {
	this := ApplicationLoadBalancer{}
	return &this
}

// GetEnabled returns the Enabled field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *ApplicationLoadBalancer) GetEnabled() (ret ApplicationLoadBalancergetEnabledRetType) {
	ret, _ = o.GetEnabledOk()
	return ret
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *ApplicationLoadBalancer) GetEnabledOk() (ret ApplicationLoadBalancergetEnabledRetType, ok bool) {
	return getApplicationLoadBalancergetEnabledAttributeTypeOk(o.Enabled)
}

// SetEnabled sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *ApplicationLoadBalancer) SetEnabled(v ApplicationLoadBalancergetEnabledRetType) {
	setApplicationLoadBalancergetEnabledAttributeType(&o.Enabled, v)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o ApplicationLoadBalancer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getApplicationLoadBalancergetEnabledAttributeTypeOk(o.Enabled); ok {
		toSerialize["Enabled"] = val
	}
	return toSerialize, nil
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type NullableApplicationLoadBalancer struct {
	value *ApplicationLoadBalancer
	isSet bool
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableApplicationLoadBalancer) Get() *ApplicationLoadBalancer {
	return v.value
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableApplicationLoadBalancer) Set(val *ApplicationLoadBalancer) {
	v.value = val
	v.isSet = true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableApplicationLoadBalancer) IsSet() bool {
	return v.isSet
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableApplicationLoadBalancer) Unset() {
	v.value = nil
	v.isSet = false
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewNullableApplicationLoadBalancer(val *ApplicationLoadBalancer) *NullableApplicationLoadBalancer {
	return &NullableApplicationLoadBalancer{value: val, isSet: true}
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableApplicationLoadBalancer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableApplicationLoadBalancer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
