/*
STACKIT Key Management Service API

### DEPRECATED! This service is no longer maintained. Please use the version v1 instead. This API provides endpoints for managing keys and key rings.

API version: 1beta.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1betaapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HttpError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpError{}

// HttpError struct for HttpError
type HttpError struct {
	// A string that gives a short information about what went wrong.
	Message              string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _HttpError HttpError

// NewHttpError instantiates a new HttpError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpError(message string) *HttpError {
	this := HttpError{}
	this.Message = message
	return &this
}

// NewHttpErrorWithDefaults instantiates a new HttpError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpErrorWithDefaults() *HttpError {
	this := HttpError{}
	return &this
}

// GetMessage returns the Message field value
func (o *HttpError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HttpError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HttpError) SetMessage(v string) {
	o.Message = v
}

func (o HttpError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HttpError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpError := _HttpError{}

	err = json.Unmarshal(data, &varHttpError)

	if err != nil {
		return err
	}

	*o = HttpError(varHttpError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHttpError struct {
	value *HttpError
	isSet bool
}

func (v NullableHttpError) Get() *HttpError {
	return v.value
}

func (v *NullableHttpError) Set(val *HttpError) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpError) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpError(val *HttpError) *NullableHttpError {
	return &NullableHttpError{value: val, isSet: true}
}

func (v NullableHttpError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
