/*
STACKIT Application Load Balancer Web Application Firewall API

Generate a Web Application Firewall (WAF) to use with Application Load Balancers (ALB). The name of the WAF configuration is used in the listener of the ALB. This will activate the WAF for that ALB. An ALB with a WAF can have OWASP core rule set enabled and in addition can have custom rule configurations. To create a WAF one first needs to create all the configurations that are referenced in the WAF configuration. Currently this only consists of a rule configuration, which is written in Seclang. Once all configurations are created and referenced in the WAF configuration it can be used with an ALB. Currently updating a WAF configuration will not update an existing ALB until the Load Balancer VMs are restarted.

API version: 1alpha.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alphaapi

import (
	"encoding/json"
)

// checks if the CRSRuleGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CRSRuleGroup{}

// CRSRuleGroup RuleGroup represents a collection of rules associated with a specific group.
type CRSRuleGroup struct {
	// A description of what this group covers.
	Description *string `json:"description,omitempty"`
	// The name for the rule group.
	GroupName *string `json:"groupName,omitempty" validate:"regexp=^[a-zA-Z\\\\(\\\\) ]+$"`
	// The list of individual rules contained within this group.
	Rules                []CRSRule `json:"rules,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CRSRuleGroup CRSRuleGroup

// NewCRSRuleGroup instantiates a new CRSRuleGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCRSRuleGroup() *CRSRuleGroup {
	this := CRSRuleGroup{}
	return &this
}

// NewCRSRuleGroupWithDefaults instantiates a new CRSRuleGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCRSRuleGroupWithDefaults() *CRSRuleGroup {
	this := CRSRuleGroup{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CRSRuleGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CRSRuleGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CRSRuleGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CRSRuleGroup) SetDescription(v string) {
	o.Description = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *CRSRuleGroup) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CRSRuleGroup) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *CRSRuleGroup) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *CRSRuleGroup) SetGroupName(v string) {
	o.GroupName = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *CRSRuleGroup) GetRules() []CRSRule {
	if o == nil || IsNil(o.Rules) {
		var ret []CRSRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CRSRuleGroup) GetRulesOk() ([]CRSRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *CRSRuleGroup) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []CRSRule and assigns it to the Rules field.
func (o *CRSRuleGroup) SetRules(v []CRSRule) {
	o.Rules = v
}

func (o CRSRuleGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CRSRuleGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.GroupName) {
		toSerialize["groupName"] = o.GroupName
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CRSRuleGroup) UnmarshalJSON(data []byte) (err error) {
	varCRSRuleGroup := _CRSRuleGroup{}

	err = json.Unmarshal(data, &varCRSRuleGroup)

	if err != nil {
		return err
	}

	*o = CRSRuleGroup(varCRSRuleGroup)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "groupName")
		delete(additionalProperties, "rules")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCRSRuleGroup struct {
	value *CRSRuleGroup
	isSet bool
}

func (v NullableCRSRuleGroup) Get() *CRSRuleGroup {
	return v.value
}

func (v *NullableCRSRuleGroup) Set(val *CRSRuleGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCRSRuleGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCRSRuleGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCRSRuleGroup(val *CRSRuleGroup) *NullableCRSRuleGroup {
	return &NullableCRSRuleGroup{value: val, isSet: true}
}

func (v NullableCRSRuleGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCRSRuleGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
