/*
STACKIT Server Update Management API

API endpoints for Server Update Operations on STACKIT Servers.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
package serverupdate

import (
	"encoding/json"
)

// checks if the UpdateSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSchedule{}

/*
	types and functions for enabled
*/

// isBoolean
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateSchedulegetEnabledAttributeType = *bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateSchedulegetEnabledArgType = bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateSchedulegetEnabledRetType = bool

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateSchedulegetEnabledAttributeTypeOk(arg UpdateSchedulegetEnabledAttributeType) (ret UpdateSchedulegetEnabledRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateSchedulegetEnabledAttributeType(arg *UpdateSchedulegetEnabledAttributeType, val UpdateSchedulegetEnabledRetType) {
	*arg = &val
}

/*
	types and functions for maintenanceWindow
*/

// isInteger
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetMaintenanceWindowAttributeType = *int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetMaintenanceWindowArgType = int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetMaintenanceWindowRetType = int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateScheduleGetMaintenanceWindowAttributeTypeOk(arg UpdateScheduleGetMaintenanceWindowAttributeType) (ret UpdateScheduleGetMaintenanceWindowRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateScheduleGetMaintenanceWindowAttributeType(arg *UpdateScheduleGetMaintenanceWindowAttributeType, val UpdateScheduleGetMaintenanceWindowRetType) {
	*arg = &val
}

/*
	types and functions for name
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetNameAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateScheduleGetNameAttributeTypeOk(arg UpdateScheduleGetNameAttributeType) (ret UpdateScheduleGetNameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateScheduleGetNameAttributeType(arg *UpdateScheduleGetNameAttributeType, val UpdateScheduleGetNameRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetNameArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetNameRetType = string

/*
	types and functions for rrule
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetRruleAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateScheduleGetRruleAttributeTypeOk(arg UpdateScheduleGetRruleAttributeType) (ret UpdateScheduleGetRruleRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateScheduleGetRruleAttributeType(arg *UpdateScheduleGetRruleAttributeType, val UpdateScheduleGetRruleRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetRruleArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetRruleRetType = string

/*
	types and functions for id
*/

// isInteger
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetIdAttributeType = *int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetIdArgType = int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateScheduleGetIdRetType = int64

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateScheduleGetIdAttributeTypeOk(arg UpdateScheduleGetIdAttributeType) (ret UpdateScheduleGetIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateScheduleGetIdAttributeType(arg *UpdateScheduleGetIdAttributeType, val UpdateScheduleGetIdRetType) {
	*arg = &val
}

// UpdateSchedule struct for UpdateSchedule
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateSchedule struct {
	// REQUIRED
	Enabled UpdateSchedulegetEnabledAttributeType `json:"enabled" required:"true"`
	// Updates start within the defined hourly window. Depending on the updates, the process may exceed this timeframe and require an automatic restart.
	// Can be cast to int32 without loss of precision.
	// REQUIRED
	MaintenanceWindow UpdateScheduleGetMaintenanceWindowAttributeType `json:"maintenanceWindow" required:"true"`
	// REQUIRED
	Name UpdateScheduleGetNameAttributeType `json:"name" required:"true"`
	// An rrule (Recurrence Rule) is a standardized string format used in iCalendar (RFC 5545) to define repeating events, and you can generate one by using a dedicated library or by using online generator tools to specify parameters like frequency, interval, and end dates
	// REQUIRED
	Rrule UpdateScheduleGetRruleAttributeType `json:"rrule" required:"true"`
	// Can be cast to int32 without loss of precision.
	// REQUIRED
	Id UpdateScheduleGetIdAttributeType `json:"id" required:"true"`
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type _UpdateSchedule UpdateSchedule

// NewUpdateSchedule instantiates a new UpdateSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewUpdateSchedule(enabled UpdateSchedulegetEnabledArgType, maintenanceWindow UpdateScheduleGetMaintenanceWindowArgType, name UpdateScheduleGetNameArgType, rrule UpdateScheduleGetRruleArgType, id UpdateScheduleGetIdArgType) *UpdateSchedule {
	this := UpdateSchedule{}
	setUpdateSchedulegetEnabledAttributeType(&this.Enabled, enabled)
	setUpdateScheduleGetMaintenanceWindowAttributeType(&this.MaintenanceWindow, maintenanceWindow)
	setUpdateScheduleGetNameAttributeType(&this.Name, name)
	setUpdateScheduleGetRruleAttributeType(&this.Rrule, rrule)
	setUpdateScheduleGetIdAttributeType(&this.Id, id)
	return &this
}

// NewUpdateScheduleWithDefaults instantiates a new UpdateSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewUpdateScheduleWithDefaults() *UpdateSchedule {
	this := UpdateSchedule{}
	return &this
}

// GetEnabled returns the Enabled field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetEnabled() (ret UpdateSchedulegetEnabledRetType) {
	ret, _ = o.GetEnabledOk()
	return ret
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetEnabledOk() (ret UpdateSchedulegetEnabledRetType, ok bool) {
	return getUpdateSchedulegetEnabledAttributeTypeOk(o.Enabled)
}

// SetEnabled sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) SetEnabled(v UpdateSchedulegetEnabledRetType) {
	setUpdateSchedulegetEnabledAttributeType(&o.Enabled, v)
}

// GetMaintenanceWindow returns the MaintenanceWindow field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetMaintenanceWindow() (ret UpdateScheduleGetMaintenanceWindowRetType) {
	ret, _ = o.GetMaintenanceWindowOk()
	return ret
}

// GetMaintenanceWindowOk returns a tuple with the MaintenanceWindow field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetMaintenanceWindowOk() (ret UpdateScheduleGetMaintenanceWindowRetType, ok bool) {
	return getUpdateScheduleGetMaintenanceWindowAttributeTypeOk(o.MaintenanceWindow)
}

// SetMaintenanceWindow sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) SetMaintenanceWindow(v UpdateScheduleGetMaintenanceWindowRetType) {
	setUpdateScheduleGetMaintenanceWindowAttributeType(&o.MaintenanceWindow, v)
}

// GetName returns the Name field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetName() (ret UpdateScheduleGetNameRetType) {
	ret, _ = o.GetNameOk()
	return ret
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetNameOk() (ret UpdateScheduleGetNameRetType, ok bool) {
	return getUpdateScheduleGetNameAttributeTypeOk(o.Name)
}

// SetName sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) SetName(v UpdateScheduleGetNameRetType) {
	setUpdateScheduleGetNameAttributeType(&o.Name, v)
}

// GetRrule returns the Rrule field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetRrule() (ret UpdateScheduleGetRruleRetType) {
	ret, _ = o.GetRruleOk()
	return ret
}

// GetRruleOk returns a tuple with the Rrule field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetRruleOk() (ret UpdateScheduleGetRruleRetType, ok bool) {
	return getUpdateScheduleGetRruleAttributeTypeOk(o.Rrule)
}

// SetRrule sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) SetRrule(v UpdateScheduleGetRruleRetType) {
	setUpdateScheduleGetRruleAttributeType(&o.Rrule, v)
}

// GetId returns the Id field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetId() (ret UpdateScheduleGetIdRetType) {
	ret, _ = o.GetIdOk()
	return ret
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) GetIdOk() (ret UpdateScheduleGetIdRetType, ok bool) {
	return getUpdateScheduleGetIdAttributeTypeOk(o.Id)
}

// SetId sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateSchedule) SetId(v UpdateScheduleGetIdRetType) {
	setUpdateScheduleGetIdAttributeType(&o.Id, v)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o UpdateSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getUpdateSchedulegetEnabledAttributeTypeOk(o.Enabled); ok {
		toSerialize["Enabled"] = val
	}
	if val, ok := getUpdateScheduleGetMaintenanceWindowAttributeTypeOk(o.MaintenanceWindow); ok {
		toSerialize["MaintenanceWindow"] = val
	}
	if val, ok := getUpdateScheduleGetNameAttributeTypeOk(o.Name); ok {
		toSerialize["Name"] = val
	}
	if val, ok := getUpdateScheduleGetRruleAttributeTypeOk(o.Rrule); ok {
		toSerialize["Rrule"] = val
	}
	if val, ok := getUpdateScheduleGetIdAttributeTypeOk(o.Id); ok {
		toSerialize["Id"] = val
	}
	return toSerialize, nil
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type NullableUpdateSchedule struct {
	value *UpdateSchedule
	isSet bool
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateSchedule) Get() *UpdateSchedule {
	return v.value
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateSchedule) Set(val *UpdateSchedule) {
	v.value = val
	v.isSet = true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateSchedule) IsSet() bool {
	return v.isSet
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewNullableUpdateSchedule(val *UpdateSchedule) *NullableUpdateSchedule {
	return &NullableUpdateSchedule{value: val, isSet: true}
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
