/*
STACKIT Server Update Management API

API endpoints for Server Update Operations on STACKIT Servers.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package serverupdate

import (
	"encoding/json"
)

// checks if the CreateUpdateSchedulePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUpdateSchedulePayload{}

// CreateUpdateSchedulePayload struct for CreateUpdateSchedulePayload
type CreateUpdateSchedulePayload struct {
	// REQUIRED
	Enabled *bool `json:"enabled"`
	// Can be cast to int32 without loss of precision.
	Id *int64 `json:"id,omitempty"`
	// Can be cast to int32 without loss of precision.
	// REQUIRED
	MaintenanceWindow *int64 `json:"maintenanceWindow"`
	// REQUIRED
	Name *string `json:"name"`
	// REQUIRED
	Rrule *string `json:"rrule"`
}

type _CreateUpdateSchedulePayload CreateUpdateSchedulePayload

// NewCreateUpdateSchedulePayload instantiates a new CreateUpdateSchedulePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUpdateSchedulePayload(enabled *bool, maintenanceWindow *int64, name *string, rrule *string) *CreateUpdateSchedulePayload {
	this := CreateUpdateSchedulePayload{}
	this.Enabled = enabled
	this.MaintenanceWindow = maintenanceWindow
	this.Name = name
	this.Rrule = rrule
	return &this
}

// NewCreateUpdateSchedulePayloadWithDefaults instantiates a new CreateUpdateSchedulePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUpdateSchedulePayloadWithDefaults() *CreateUpdateSchedulePayload {
	this := CreateUpdateSchedulePayload{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CreateUpdateSchedulePayload) GetEnabled() *bool {
	if o == nil || IsNil(o.Enabled) {
		var ret *bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSchedulePayload) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateUpdateSchedulePayload) SetEnabled(v *bool) {
	o.Enabled = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateUpdateSchedulePayload) GetId() *int64 {
	if o == nil || IsNil(o.Id) {
		var ret *int64
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUpdateSchedulePayload) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateUpdateSchedulePayload) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *CreateUpdateSchedulePayload) SetId(v *int64) {
	o.Id = v
}

// GetMaintenanceWindow returns the MaintenanceWindow field value
func (o *CreateUpdateSchedulePayload) GetMaintenanceWindow() *int64 {
	if o == nil || IsNil(o.MaintenanceWindow) {
		var ret *int64
		return ret
	}

	return o.MaintenanceWindow
}

// GetMaintenanceWindowOk returns a tuple with the MaintenanceWindow field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSchedulePayload) GetMaintenanceWindowOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaintenanceWindow, true
}

// SetMaintenanceWindow sets field value
func (o *CreateUpdateSchedulePayload) SetMaintenanceWindow(v *int64) {
	o.MaintenanceWindow = v
}

// GetName returns the Name field value
func (o *CreateUpdateSchedulePayload) GetName() *string {
	if o == nil || IsNil(o.Name) {
		var ret *string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSchedulePayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *CreateUpdateSchedulePayload) SetName(v *string) {
	o.Name = v
}

// GetRrule returns the Rrule field value
func (o *CreateUpdateSchedulePayload) GetRrule() *string {
	if o == nil || IsNil(o.Rrule) {
		var ret *string
		return ret
	}

	return o.Rrule
}

// GetRruleOk returns a tuple with the Rrule field value
// and a boolean to check if the value has been set.
func (o *CreateUpdateSchedulePayload) GetRruleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rrule, true
}

// SetRrule sets field value
func (o *CreateUpdateSchedulePayload) SetRrule(v *string) {
	o.Rrule = v
}

func (o CreateUpdateSchedulePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["maintenanceWindow"] = o.MaintenanceWindow
	toSerialize["name"] = o.Name
	toSerialize["rrule"] = o.Rrule
	return toSerialize, nil
}

type NullableCreateUpdateSchedulePayload struct {
	value *CreateUpdateSchedulePayload
	isSet bool
}

func (v NullableCreateUpdateSchedulePayload) Get() *CreateUpdateSchedulePayload {
	return v.value
}

func (v *NullableCreateUpdateSchedulePayload) Set(val *CreateUpdateSchedulePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUpdateSchedulePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUpdateSchedulePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUpdateSchedulePayload(val *CreateUpdateSchedulePayload) *NullableCreateUpdateSchedulePayload {
	return &NullableCreateUpdateSchedulePayload{value: val, isSet: true}
}

func (v NullableCreateUpdateSchedulePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUpdateSchedulePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
