/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

type BasicAuth struct {
	// REQUIRED
	Password *string `json:"password"`
	// REQUIRED
	Username *string `json:"username"`
}
