/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
package observability

import (
	"encoding/json"
)

// checks if the UpdateAlertRecordPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRecordPayload{}

/*
	types and functions for expr
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetExprAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateAlertRecordPayloadGetExprAttributeTypeOk(arg UpdateAlertRecordPayloadGetExprAttributeType) (ret UpdateAlertRecordPayloadGetExprRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateAlertRecordPayloadGetExprAttributeType(arg *UpdateAlertRecordPayloadGetExprAttributeType, val UpdateAlertRecordPayloadGetExprRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetExprArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetExprRetType = string

/*
	types and functions for labels
*/

// isFreeform
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetLabelsAttributeType = *map[string]interface{}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetLabelsArgType = map[string]interface{}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayloadGetLabelsRetType = map[string]interface{}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getUpdateAlertRecordPayloadGetLabelsAttributeTypeOk(arg UpdateAlertRecordPayloadGetLabelsAttributeType) (ret UpdateAlertRecordPayloadGetLabelsRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setUpdateAlertRecordPayloadGetLabelsAttributeType(arg *UpdateAlertRecordPayloadGetLabelsAttributeType, val UpdateAlertRecordPayloadGetLabelsRetType) {
	*arg = &val
}

// UpdateAlertRecordPayload Record. `Additional Validators:` * total config (all alert groups/rules/records) should not be bigger than 500000 characters as string since this the limitation of prometheus.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type UpdateAlertRecordPayload struct {
	// The PromQL expression to evaluate. Every evaluation cycle this is evaluated at the current time, and all resultant time series become pending/firing alerts.
	// REQUIRED
	Expr UpdateAlertRecordPayloadGetExprAttributeType `json:"expr" required:"true"`
	// map of key:value. Labels to add or overwrite for each alert. `Additional Validators:` * should not contain more than 5 keys * each key and value should not be longer than 200 characters
	Labels UpdateAlertRecordPayloadGetLabelsAttributeType `json:"labels,omitempty"`
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type _UpdateAlertRecordPayload UpdateAlertRecordPayload

// NewUpdateAlertRecordPayload instantiates a new UpdateAlertRecordPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewUpdateAlertRecordPayload(expr UpdateAlertRecordPayloadGetExprArgType) *UpdateAlertRecordPayload {
	this := UpdateAlertRecordPayload{}
	setUpdateAlertRecordPayloadGetExprAttributeType(&this.Expr, expr)
	return &this
}

// NewUpdateAlertRecordPayloadWithDefaults instantiates a new UpdateAlertRecordPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewUpdateAlertRecordPayloadWithDefaults() *UpdateAlertRecordPayload {
	this := UpdateAlertRecordPayload{}
	return &this
}

// GetExpr returns the Expr field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) GetExpr() (ret UpdateAlertRecordPayloadGetExprRetType) {
	ret, _ = o.GetExprOk()
	return ret
}

// GetExprOk returns a tuple with the Expr field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) GetExprOk() (ret UpdateAlertRecordPayloadGetExprRetType, ok bool) {
	return getUpdateAlertRecordPayloadGetExprAttributeTypeOk(o.Expr)
}

// SetExpr sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) SetExpr(v UpdateAlertRecordPayloadGetExprRetType) {
	setUpdateAlertRecordPayloadGetExprAttributeType(&o.Expr, v)
}

// GetLabels returns the Labels field value if set, zero value otherwise.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) GetLabels() (res UpdateAlertRecordPayloadGetLabelsRetType) {
	res, _ = o.GetLabelsOk()
	return
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) GetLabelsOk() (ret UpdateAlertRecordPayloadGetLabelsRetType, ok bool) {
	return getUpdateAlertRecordPayloadGetLabelsAttributeTypeOk(o.Labels)
}

// HasLabels returns a boolean if a field has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) HasLabels() bool {
	_, ok := o.GetLabelsOk()
	return ok
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *UpdateAlertRecordPayload) SetLabels(v UpdateAlertRecordPayloadGetLabelsRetType) {
	setUpdateAlertRecordPayloadGetLabelsAttributeType(&o.Labels, v)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o UpdateAlertRecordPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getUpdateAlertRecordPayloadGetExprAttributeTypeOk(o.Expr); ok {
		toSerialize["Expr"] = val
	}
	if val, ok := getUpdateAlertRecordPayloadGetLabelsAttributeTypeOk(o.Labels); ok {
		toSerialize["Labels"] = val
	}
	return toSerialize, nil
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type NullableUpdateAlertRecordPayload struct {
	value *UpdateAlertRecordPayload
	isSet bool
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateAlertRecordPayload) Get() *UpdateAlertRecordPayload {
	return v.value
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateAlertRecordPayload) Set(val *UpdateAlertRecordPayload) {
	v.value = val
	v.isSet = true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateAlertRecordPayload) IsSet() bool {
	return v.isSet
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateAlertRecordPayload) Unset() {
	v.value = nil
	v.isSet = false
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewNullableUpdateAlertRecordPayload(val *UpdateAlertRecordPayload) *NullableUpdateAlertRecordPayload {
	return &NullableUpdateAlertRecordPayload{value: val, isSet: true}
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableUpdateAlertRecordPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableUpdateAlertRecordPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
