/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package observability

// CreateCredentialsResponse struct for CreateCredentialsResponse
type CreateCredentialsResponse struct {
	// REQUIRED
	Credentials *Credentials `json:"credentials"`
	// REQUIRED
	Message *string `json:"message"`
}
