/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package observability

// BasicAuth struct for BasicAuth
type BasicAuth struct {
	// REQUIRED
	Password *string `json:"password"`
	// REQUIRED
	Username *string `json:"username"`
}
