/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package observability

import (
	"encoding/json"
	"fmt"
)

// checks if the PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner{}

/*
	types and functions for action
*/

// isEnum

// PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction Action to perform based on regex matching. `Additional Validators:` * if action is replace, targetLabel needs to be in body
// value type for enums
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction string

// List of Action
const (
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_REPLACE   PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "replace"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_KEEP      PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "keep"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_DROP      PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "drop"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_HASHMOD   PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "hashmod"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_LABELMAP  PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "labelmap"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_LABELDROP PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "labeldrop"
	PARTIALUPDATESCRAPECONFIGSREQUESTINNERMETRICSRELABELCONFIGSINNERACTION_LABELKEEP PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "labelkeep"
)

// All allowed values of PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner enum
var AllowedPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionEnumValues = []PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction{
	"replace",
	"keep",
	"drop",
	"hashmod",
	"labelmap",
	"labeldrop",
	"labelkeep",
}

func (v *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) UnmarshalJSON(src []byte) error {
	// use a type alias to prevent infinite recursion during unmarshal,
	// see https://biscuit.ninja/posts/go-avoid-an-infitine-loop-with-custom-json-unmarshallers
	type TmpJson PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction
	var value TmpJson
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	// Allow unmarshalling zero value for testing purposes
	var zeroValue TmpJson
	if value == zeroValue {
		return nil
	}
	enumTypeValue := PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction(value)
	for _, existing := range AllowedPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner", value)
}

// NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionFromValue returns a pointer to a valid PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionFromValue(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) (*PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction, error) {
	ev := PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction: valid values are %v", v, AllowedPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) IsValid() bool {
	for _, existing := range AllowedPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ActionAction value
func (v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) Ptr() *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction {
	return &v
}

type NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction struct {
	value *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction
	isSet bool
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) Get() *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction {
	return v.value
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) Set(val *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction(val *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction {
	return &NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction{value: val, isSet: true}
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType = *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionArgType = PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType = PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType) {
	*arg = &val
}

/*
	types and functions for modulus
*/

// isNumber
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType = *float64
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusArgType = float64
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType = float64

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType) {
	*arg = &val
}

/*
	types and functions for regex
*/

// isNotNullableString
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType = *string

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType) {
	*arg = &val
}

type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexArgType = string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType = string

/*
	types and functions for replacement
*/

// isNotNullableString
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType = *string

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType) {
	*arg = &val
}

type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementArgType = string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType = string

/*
	types and functions for separator
*/

// isNotNullableString
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType = *string

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType) {
	*arg = &val
}

type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorArgType = string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType = string

/*
	types and functions for sourceLabels
*/

// isArray
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType = *[]string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsArgType = []string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType = []string

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType) {
	*arg = &val
}

/*
	types and functions for targetLabel
*/

// isNotNullableString
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType = *string

func getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeTypeOk(arg PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType) (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType(arg *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType, val PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType) {
	*arg = &val
}

type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelArgType = string
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType = string

// PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner struct for PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner
type PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner struct {
	// Action to perform based on regex matching. `Additional Validators:` * if action is replace, targetLabel needs to be in body
	Action PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType `json:"action,omitempty"`
	// Modulus to take of the hash of the source label values.
	Modulus PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType `json:"modulus,omitempty"`
	// Regular expression against which the extracted value is matched.
	Regex PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType `json:"regex,omitempty"`
	// Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available.
	Replacement PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType `json:"replacement,omitempty"`
	// Separator placed between concatenated source label values.
	Separator PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType `json:"separator,omitempty"`
	// The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.
	SourceLabels PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType `json:"sourceLabels,omitempty"`
	// Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.
	TargetLabel PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType `json:"targetLabel,omitempty"`
}

// NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner instantiates a new PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner() *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner {
	this := PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner{}
	return &this
}

// NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerWithDefaults instantiates a new PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerWithDefaults() *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner {
	this := PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner{}
	var action PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerAction = "replace"
	this.Action = &action
	var regex string = ".*"
	this.Regex = &regex
	var replacement string = "$1"
	this.Replacement = &replacement
	var separator string = ";"
	this.Separator = &separator
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetAction() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType) {
	res, _ = o.GetActionOk()
	return
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetActionOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeTypeOk(o.Action)
}

// HasAction returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasAction() bool {
	_, ok := o.GetActionOk()
	return ok
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetAction(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeType(&o.Action, v)
}

// GetModulus returns the Modulus field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetModulus() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType) {
	res, _ = o.GetModulusOk()
	return
}

// GetModulusOk returns a tuple with the Modulus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetModulusOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeTypeOk(o.Modulus)
}

// HasModulus returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasModulus() bool {
	_, ok := o.GetModulusOk()
	return ok
}

// SetModulus gets a reference to the given float64 and assigns it to the Modulus field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetModulus(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeType(&o.Modulus, v)
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetRegex() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType) {
	res, _ = o.GetRegexOk()
	return
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetRegexOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeTypeOk(o.Regex)
}

// HasRegex returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasRegex() bool {
	_, ok := o.GetRegexOk()
	return ok
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetRegex(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeType(&o.Regex, v)
}

// GetReplacement returns the Replacement field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetReplacement() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType) {
	res, _ = o.GetReplacementOk()
	return
}

// GetReplacementOk returns a tuple with the Replacement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetReplacementOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeTypeOk(o.Replacement)
}

// HasReplacement returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasReplacement() bool {
	_, ok := o.GetReplacementOk()
	return ok
}

// SetReplacement gets a reference to the given string and assigns it to the Replacement field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetReplacement(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeType(&o.Replacement, v)
}

// GetSeparator returns the Separator field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetSeparator() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType) {
	res, _ = o.GetSeparatorOk()
	return
}

// GetSeparatorOk returns a tuple with the Separator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetSeparatorOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeTypeOk(o.Separator)
}

// HasSeparator returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasSeparator() bool {
	_, ok := o.GetSeparatorOk()
	return ok
}

// SetSeparator gets a reference to the given string and assigns it to the Separator field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetSeparator(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeType(&o.Separator, v)
}

// GetSourceLabels returns the SourceLabels field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetSourceLabels() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType) {
	res, _ = o.GetSourceLabelsOk()
	return
}

// GetSourceLabelsOk returns a tuple with the SourceLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetSourceLabelsOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeTypeOk(o.SourceLabels)
}

// HasSourceLabels returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasSourceLabels() bool {
	_, ok := o.GetSourceLabelsOk()
	return ok
}

// SetSourceLabels gets a reference to the given []string and assigns it to the SourceLabels field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetSourceLabels(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeType(&o.SourceLabels, v)
}

// GetTargetLabel returns the TargetLabel field value if set, zero value otherwise.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetTargetLabel() (res PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType) {
	res, _ = o.GetTargetLabelOk()
	return
}

// GetTargetLabelOk returns a tuple with the TargetLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) GetTargetLabelOk() (ret PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType, ok bool) {
	return getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeTypeOk(o.TargetLabel)
}

// HasTargetLabel returns a boolean if a field has been set.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) HasTargetLabel() bool {
	_, ok := o.GetTargetLabelOk()
	return ok
}

// SetTargetLabel gets a reference to the given string and assigns it to the TargetLabel field.
func (o *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) SetTargetLabel(v PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelRetType) {
	setPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeType(&o.TargetLabel, v)
}

func (o PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetActionAttributeTypeOk(o.Action); ok {
		toSerialize["Action"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetModulusAttributeTypeOk(o.Modulus); ok {
		toSerialize["Modulus"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetRegexAttributeTypeOk(o.Regex); ok {
		toSerialize["Regex"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetReplacementAttributeTypeOk(o.Replacement); ok {
		toSerialize["Replacement"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSeparatorAttributeTypeOk(o.Separator); ok {
		toSerialize["Separator"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetSourceLabelsAttributeTypeOk(o.SourceLabels); ok {
		toSerialize["SourceLabels"] = val
	}
	if val, ok := getPartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInnerGetTargetLabelAttributeTypeOk(o.TargetLabel); ok {
		toSerialize["TargetLabel"] = val
	}
	return toSerialize, nil
}

type NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner struct {
	value *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner
	isSet bool
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) Get() *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner {
	return v.value
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) Set(val *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner(val *PartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner {
	return &NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner{value: val, isSet: true}
}

func (v NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartialUpdateScrapeConfigsRequestInnerMetricsRelabelConfigsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
