/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package observability

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateACLPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateACLPayload{}

/*
	types and functions for acl
*/

// isArray
type UpdateACLPayloadGetAclAttributeType = *[]string
type UpdateACLPayloadGetAclArgType = []string
type UpdateACLPayloadGetAclRetType = []string

func getUpdateACLPayloadGetAclAttributeTypeOk(arg UpdateACLPayloadGetAclAttributeType) (ret UpdateACLPayloadGetAclRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setUpdateACLPayloadGetAclAttributeType(arg *UpdateACLPayloadGetAclAttributeType, val UpdateACLPayloadGetAclRetType) {
	*arg = &val
}

// UpdateACLPayload List of cidr. Send empty string to remove acl.
type UpdateACLPayload struct {
	// list of cidr
	// REQUIRED
	Acl UpdateACLPayloadGetAclAttributeType `json:"acl"`
}

type _UpdateACLPayload UpdateACLPayload

// NewUpdateACLPayload instantiates a new UpdateACLPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateACLPayload(acl UpdateACLPayloadGetAclArgType) *UpdateACLPayload {
	this := UpdateACLPayload{}
	setUpdateACLPayloadGetAclAttributeType(&this.Acl, acl)
	return &this
}

// NewUpdateACLPayloadWithDefaults instantiates a new UpdateACLPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateACLPayloadWithDefaults() *UpdateACLPayload {
	this := UpdateACLPayload{}
	return &this
}

// GetAcl returns the Acl field value
func (o *UpdateACLPayload) GetAcl() (ret UpdateACLPayloadGetAclRetType) {
	ret, _ = o.GetAclOk()
	return ret
}

// GetAclOk returns a tuple with the Acl field value
// and a boolean to check if the value has been set.
func (o *UpdateACLPayload) GetAclOk() (ret UpdateACLPayloadGetAclRetType, ok bool) {
	return getUpdateACLPayloadGetAclAttributeTypeOk(o.Acl)
}

// SetAcl sets field value
func (o *UpdateACLPayload) SetAcl(v UpdateACLPayloadGetAclRetType) {
	setUpdateACLPayloadGetAclAttributeType(&o.Acl, v)
}

func (o UpdateACLPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateACLPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getUpdateACLPayloadGetAclAttributeTypeOk(o.Acl); ok {
		toSerialize["Acl"] = val
	}
	return toSerialize, nil
}

func (o *UpdateACLPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"acl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateACLPayload := _UpdateACLPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateACLPayload)

	if err != nil {
		return err
	}

	*o = UpdateACLPayload(varUpdateACLPayload)

	return err
}

type NullableUpdateACLPayload struct {
	value *UpdateACLPayload
	isSet bool
}

func (v NullableUpdateACLPayload) Get() *UpdateACLPayload {
	return v.value
}

func (v *NullableUpdateACLPayload) Set(val *UpdateACLPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateACLPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateACLPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateACLPayload(val *UpdateACLPayload) *NullableUpdateACLPayload {
	return &NullableUpdateACLPayload{value: val, isSet: true}
}

func (v NullableUpdateACLPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateACLPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
