/*
STACKIT Observability API

API endpoints for Observability on STACKIT

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
package observability

import (
	"encoding/json"
)

// checks if the CertCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertCheckResponse{}

/*
	types and functions for certCheck
*/

// isModel
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertCheckAttributeType = *CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertCheckArgType = CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertCheckRetType = CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getCertCheckResponseGetCertCheckAttributeTypeOk(arg CertCheckResponseGetCertCheckAttributeType) (ret CertCheckResponseGetCertCheckRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setCertCheckResponseGetCertCheckAttributeType(arg *CertCheckResponseGetCertCheckAttributeType, val CertCheckResponseGetCertCheckRetType) {
	*arg = &val
}

/*
	types and functions for certChecks
*/

// isArray
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertChecksAttributeType = *[]CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertChecksArgType = []CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetCertChecksRetType = []CertCheckChildResponse

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getCertCheckResponseGetCertChecksAttributeTypeOk(arg CertCheckResponseGetCertChecksAttributeType) (ret CertCheckResponseGetCertChecksRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setCertCheckResponseGetCertChecksAttributeType(arg *CertCheckResponseGetCertChecksAttributeType, val CertCheckResponseGetCertChecksRetType) {
	*arg = &val
}

/*
	types and functions for message
*/

// isNotNullableString
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetMessageAttributeType = *string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func getCertCheckResponseGetMessageAttributeTypeOk(arg CertCheckResponseGetMessageAttributeType) (ret CertCheckResponseGetMessageRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func setCertCheckResponseGetMessageAttributeType(arg *CertCheckResponseGetMessageAttributeType, val CertCheckResponseGetMessageRetType) {
	*arg = &val
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetMessageArgType = string

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponseGetMessageRetType = string

// CertCheckResponse struct for CertCheckResponse
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type CertCheckResponse struct {
	CertCheck CertCheckResponseGetCertCheckAttributeType `json:"certCheck,omitempty"`
	// REQUIRED
	CertChecks CertCheckResponseGetCertChecksAttributeType `json:"certChecks" required:"true"`
	// REQUIRED
	Message CertCheckResponseGetMessageAttributeType `json:"message" required:"true"`
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type _CertCheckResponse CertCheckResponse

// NewCertCheckResponse instantiates a new CertCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewCertCheckResponse(certChecks CertCheckResponseGetCertChecksArgType, message CertCheckResponseGetMessageArgType) *CertCheckResponse {
	this := CertCheckResponse{}
	setCertCheckResponseGetCertChecksAttributeType(&this.CertChecks, certChecks)
	setCertCheckResponseGetMessageAttributeType(&this.Message, message)
	return &this
}

// NewCertCheckResponseWithDefaults instantiates a new CertCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewCertCheckResponseWithDefaults() *CertCheckResponse {
	this := CertCheckResponse{}
	return &this
}

// GetCertCheck returns the CertCheck field value if set, zero value otherwise.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetCertCheck() (res CertCheckResponseGetCertCheckRetType) {
	res, _ = o.GetCertCheckOk()
	return
}

// GetCertCheckOk returns a tuple with the CertCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetCertCheckOk() (ret CertCheckResponseGetCertCheckRetType, ok bool) {
	return getCertCheckResponseGetCertCheckAttributeTypeOk(o.CertCheck)
}

// HasCertCheck returns a boolean if a field has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) HasCertCheck() bool {
	_, ok := o.GetCertCheckOk()
	return ok
}

// SetCertCheck gets a reference to the given CertCheckChildResponse and assigns it to the CertCheck field.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) SetCertCheck(v CertCheckResponseGetCertCheckRetType) {
	setCertCheckResponseGetCertCheckAttributeType(&o.CertCheck, v)
}

// GetCertChecks returns the CertChecks field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetCertChecks() (ret CertCheckResponseGetCertChecksRetType) {
	ret, _ = o.GetCertChecksOk()
	return ret
}

// GetCertChecksOk returns a tuple with the CertChecks field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetCertChecksOk() (ret CertCheckResponseGetCertChecksRetType, ok bool) {
	return getCertCheckResponseGetCertChecksAttributeTypeOk(o.CertChecks)
}

// SetCertChecks sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) SetCertChecks(v CertCheckResponseGetCertChecksRetType) {
	setCertCheckResponseGetCertChecksAttributeType(&o.CertChecks, v)
}

// GetMessage returns the Message field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetMessage() (ret CertCheckResponseGetMessageRetType) {
	ret, _ = o.GetMessageOk()
	return ret
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) GetMessageOk() (ret CertCheckResponseGetMessageRetType, ok bool) {
	return getCertCheckResponseGetMessageAttributeTypeOk(o.Message)
}

// SetMessage sets field value
// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o *CertCheckResponse) SetMessage(v CertCheckResponseGetMessageRetType) {
	setCertCheckResponseGetMessageAttributeType(&o.Message, v)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (o CertCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getCertCheckResponseGetCertCheckAttributeTypeOk(o.CertCheck); ok {
		toSerialize["CertCheck"] = val
	}
	if val, ok := getCertCheckResponseGetCertChecksAttributeTypeOk(o.CertChecks); ok {
		toSerialize["CertChecks"] = val
	}
	if val, ok := getCertCheckResponseGetMessageAttributeTypeOk(o.Message); ok {
		toSerialize["Message"] = val
	}
	return toSerialize, nil
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
type NullableCertCheckResponse struct {
	value *CertCheckResponse
	isSet bool
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableCertCheckResponse) Get() *CertCheckResponse {
	return v.value
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableCertCheckResponse) Set(val *CertCheckResponse) {
	v.value = val
	v.isSet = true
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableCertCheckResponse) IsSet() bool {
	return v.isSet
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableCertCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func NewNullableCertCheckResponse(val *CertCheckResponse) *NullableCertCheckResponse {
	return &NullableCertCheckResponse{value: val, isSet: true}
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v NullableCertCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

// Deprecated: Will be removed after 2026-09-30. Move to the packages generated for each available API version instead
func (v *NullableCertCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
