/*
STACKIT Service Account API

API to manage Service Accounts and their Access Tokens.  ### System for Cross-domain Identity Management (SCIM) Service Account Service offers SCIM APIs to query state. The SCIM protocol was created as standard for  automating the exchange of user identity information between identity domains, or IT systems. Service accounts  are be handled as indentites similar to SCIM users. A custom SCIM schema has been created: `/ServiceAccounts`  #### Syntax ##### Attribute operators | OPERATOR | DESCRIPTION              | |----------|--------------------------| | eq       | equal                    | | ne       | not equal                | | co       | contains                 | | sw       | starts with              | | ew       | ends with                |  ##### Logical operators | OPERATOR | DESCRIPTION              | |----------|--------------------------| | and      | logical \"and\"            | | or       | logical \"or\"             |  ##### Grouping operators | OPERATOR | DESCRIPTION              | |----------|--------------------------| | ()       | precending grouping      |  ##### Example ``` filter=email eq \"my-service-account-aBc2defg@sa.stackit.cloud\" filter=email ne \"my-service-account-aBc2defg@sa.stackit.cloud\" filter=email co \"my-service-account\" filter=name sw \"my\" filter=name ew \"account\" filter=email co \"my-service-account\" and name sw \"my\" filter=email co \"my-service-account\" and (name sw \"my\" or name ew \"account\") ```  #### Sorting  > Sorting is optional  | PARAMETER | DESCRIPTION                          | |-----------|--------------------------------------| | sortBy    | attribute response is ordered by     | | sortOrder | 'ASCENDING' (default) or 'DESCENDING'|  #### Pagination  | PARAMETER    | DESCRIPTION                                  | |--------------|----------------------------------------------| | startIndex   | index of first query result, default: 1      | | count        | maximum number of query results, default: 100|

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2api

import (
	"encoding/json"
	"fmt"
)

// GetServiceAccountKeyFormatParameter the model 'GetServiceAccountKeyFormatParameter'
type GetServiceAccountKeyFormatParameter string

// List of GetServiceAccountKey_format_parameter
const (
	GETSERVICEACCOUNTKEYFORMATPARAMETER_X509_PEM                 GetServiceAccountKeyFormatParameter = "X509_PEM"
	GETSERVICEACCOUNTKEYFORMATPARAMETER_UNKNOWN_DEFAULT_OPEN_API GetServiceAccountKeyFormatParameter = "unknown_default_open_api"
)

// All allowed values of GetServiceAccountKeyFormatParameter enum
var AllowedGetServiceAccountKeyFormatParameterEnumValues = []GetServiceAccountKeyFormatParameter{
	"X509_PEM",
	"unknown_default_open_api",
}

func (v *GetServiceAccountKeyFormatParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GetServiceAccountKeyFormatParameter(value)
	for _, existing := range AllowedGetServiceAccountKeyFormatParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = GETSERVICEACCOUNTKEYFORMATPARAMETER_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewGetServiceAccountKeyFormatParameterFromValue returns a pointer to a valid GetServiceAccountKeyFormatParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGetServiceAccountKeyFormatParameterFromValue(v string) (*GetServiceAccountKeyFormatParameter, error) {
	ev := GetServiceAccountKeyFormatParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GetServiceAccountKeyFormatParameter: valid values are %v", v, AllowedGetServiceAccountKeyFormatParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GetServiceAccountKeyFormatParameter) IsValid() bool {
	for _, existing := range AllowedGetServiceAccountKeyFormatParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GetServiceAccountKey_format_parameter value
func (v GetServiceAccountKeyFormatParameter) Ptr() *GetServiceAccountKeyFormatParameter {
	return &v
}

type NullableGetServiceAccountKeyFormatParameter struct {
	value *GetServiceAccountKeyFormatParameter
	isSet bool
}

func (v NullableGetServiceAccountKeyFormatParameter) Get() *GetServiceAccountKeyFormatParameter {
	return v.value
}

func (v *NullableGetServiceAccountKeyFormatParameter) Set(val *GetServiceAccountKeyFormatParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServiceAccountKeyFormatParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServiceAccountKeyFormatParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServiceAccountKeyFormatParameter(val *GetServiceAccountKeyFormatParameter) *NullableGetServiceAccountKeyFormatParameter {
	return &NullableGetServiceAccountKeyFormatParameter{value: val, isSet: true}
}

func (v NullableGetServiceAccountKeyFormatParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServiceAccountKeyFormatParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
