/*
STACKIT Model Serving API

This API provides endpoints for the model serving api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package modelserving

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTokenResponse{}

/*
	types and functions for message
*/

// isNotNullableString
type UpdateTokenResponseGetMessageAttributeType = *string

func getUpdateTokenResponseGetMessageAttributeTypeOk(arg UpdateTokenResponseGetMessageAttributeType) (ret UpdateTokenResponseGetMessageRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setUpdateTokenResponseGetMessageAttributeType(arg *UpdateTokenResponseGetMessageAttributeType, val UpdateTokenResponseGetMessageRetType) {
	*arg = &val
}

type UpdateTokenResponseGetMessageArgType = string
type UpdateTokenResponseGetMessageRetType = string

/*
	types and functions for token
*/

// isModel
type UpdateTokenResponseGetTokenAttributeType = *Token
type UpdateTokenResponseGetTokenArgType = Token
type UpdateTokenResponseGetTokenRetType = Token

func getUpdateTokenResponseGetTokenAttributeTypeOk(arg UpdateTokenResponseGetTokenAttributeType) (ret UpdateTokenResponseGetTokenRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setUpdateTokenResponseGetTokenAttributeType(arg *UpdateTokenResponseGetTokenAttributeType, val UpdateTokenResponseGetTokenRetType) {
	*arg = &val
}

// UpdateTokenResponse struct for UpdateTokenResponse
type UpdateTokenResponse struct {
	Message UpdateTokenResponseGetMessageAttributeType `json:"message,omitempty"`
	// REQUIRED
	Token UpdateTokenResponseGetTokenAttributeType `json:"token"`
}

type _UpdateTokenResponse UpdateTokenResponse

// NewUpdateTokenResponse instantiates a new UpdateTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTokenResponse(token UpdateTokenResponseGetTokenArgType) *UpdateTokenResponse {
	this := UpdateTokenResponse{}
	setUpdateTokenResponseGetTokenAttributeType(&this.Token, token)
	return &this
}

// NewUpdateTokenResponseWithDefaults instantiates a new UpdateTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTokenResponseWithDefaults() *UpdateTokenResponse {
	this := UpdateTokenResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateTokenResponse) GetMessage() (res UpdateTokenResponseGetMessageRetType) {
	res, _ = o.GetMessageOk()
	return
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTokenResponse) GetMessageOk() (ret UpdateTokenResponseGetMessageRetType, ok bool) {
	return getUpdateTokenResponseGetMessageAttributeTypeOk(o.Message)
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateTokenResponse) HasMessage() bool {
	_, ok := o.GetMessageOk()
	return ok
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateTokenResponse) SetMessage(v UpdateTokenResponseGetMessageRetType) {
	setUpdateTokenResponseGetMessageAttributeType(&o.Message, v)
}

// GetToken returns the Token field value
func (o *UpdateTokenResponse) GetToken() (ret UpdateTokenResponseGetTokenRetType) {
	ret, _ = o.GetTokenOk()
	return ret
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *UpdateTokenResponse) GetTokenOk() (ret UpdateTokenResponseGetTokenRetType, ok bool) {
	return getUpdateTokenResponseGetTokenAttributeTypeOk(o.Token)
}

// SetToken sets field value
func (o *UpdateTokenResponse) SetToken(v UpdateTokenResponseGetTokenRetType) {
	setUpdateTokenResponseGetTokenAttributeType(&o.Token, v)
}

func (o UpdateTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getUpdateTokenResponseGetMessageAttributeTypeOk(o.Message); ok {
		toSerialize["Message"] = val
	}
	if val, ok := getUpdateTokenResponseGetTokenAttributeTypeOk(o.Token); ok {
		toSerialize["Token"] = val
	}
	return toSerialize, nil
}

func (o *UpdateTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTokenResponse := _UpdateTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTokenResponse)

	if err != nil {
		return err
	}

	*o = UpdateTokenResponse(varUpdateTokenResponse)

	return err
}

type NullableUpdateTokenResponse struct {
	value *UpdateTokenResponse
	isSet bool
}

func (v NullableUpdateTokenResponse) Get() *UpdateTokenResponse {
	return v.value
}

func (v *NullableUpdateTokenResponse) Set(val *UpdateTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTokenResponse(val *UpdateTokenResponse) *NullableUpdateTokenResponse {
	return &NullableUpdateTokenResponse{value: val, isSet: true}
}

func (v NullableUpdateTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
