/*
STACKIT Marketplace API

API to manage STACKIT Marketplace.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackitmarketplace

import (
	"encoding/json"
)

// checks if the ProjectId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectId{}

// ProjectId The associated consumer project ID.
type ProjectId struct {
}

// NewProjectId instantiates a new ProjectId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectId() *ProjectId {
	this := ProjectId{}
	return &this
}

// NewProjectIdWithDefaults instantiates a new ProjectId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectIdWithDefaults() *ProjectId {
	this := ProjectId{}
	return &this
}

func (o ProjectId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableProjectId struct {
	value *ProjectId
	isSet bool
}

func (v NullableProjectId) Get() *ProjectId {
	return v.value
}

func (v *NullableProjectId) Set(val *ProjectId) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectId) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectId(val *ProjectId) *NullableProjectId {
	return &NullableProjectId{value: val, isSet: true}
}

func (v NullableProjectId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
