/*
STACKIT Marketplace API

API to manage STACKIT Marketplace.

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackitmarketplace

import (
	"encoding/json"
)

// checks if the ContactSalesContactSales type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactSalesContactSales{}

/*
	types and functions for companyName
*/

// isNotNullableString
type ContactSalesContactSalesGetCompanyNameAttributeType = *string

func getContactSalesContactSalesGetCompanyNameAttributeTypeOk(arg ContactSalesContactSalesGetCompanyNameAttributeType) (ret ContactSalesContactSalesGetCompanyNameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setContactSalesContactSalesGetCompanyNameAttributeType(arg *ContactSalesContactSalesGetCompanyNameAttributeType, val ContactSalesContactSalesGetCompanyNameRetType) {
	*arg = &val
}

type ContactSalesContactSalesGetCompanyNameArgType = string
type ContactSalesContactSalesGetCompanyNameRetType = string

/*
	types and functions for contactEmail
*/

// isNotNullableString
type ContactSalesContactSalesGetContactEmailAttributeType = *string

func getContactSalesContactSalesGetContactEmailAttributeTypeOk(arg ContactSalesContactSalesGetContactEmailAttributeType) (ret ContactSalesContactSalesGetContactEmailRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setContactSalesContactSalesGetContactEmailAttributeType(arg *ContactSalesContactSalesGetContactEmailAttributeType, val ContactSalesContactSalesGetContactEmailRetType) {
	*arg = &val
}

type ContactSalesContactSalesGetContactEmailArgType = string
type ContactSalesContactSalesGetContactEmailRetType = string

/*
	types and functions for fullName
*/

// isNotNullableString
type ContactSalesContactSalesGetFullNameAttributeType = *string

func getContactSalesContactSalesGetFullNameAttributeTypeOk(arg ContactSalesContactSalesGetFullNameAttributeType) (ret ContactSalesContactSalesGetFullNameRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setContactSalesContactSalesGetFullNameAttributeType(arg *ContactSalesContactSalesGetFullNameAttributeType, val ContactSalesContactSalesGetFullNameRetType) {
	*arg = &val
}

type ContactSalesContactSalesGetFullNameArgType = string
type ContactSalesContactSalesGetFullNameRetType = string

/*
	types and functions for message
*/

// isNotNullableString
type ContactSalesContactSalesGetMessageAttributeType = *string

func getContactSalesContactSalesGetMessageAttributeTypeOk(arg ContactSalesContactSalesGetMessageAttributeType) (ret ContactSalesContactSalesGetMessageRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setContactSalesContactSalesGetMessageAttributeType(arg *ContactSalesContactSalesGetMessageAttributeType, val ContactSalesContactSalesGetMessageRetType) {
	*arg = &val
}

type ContactSalesContactSalesGetMessageArgType = string
type ContactSalesContactSalesGetMessageRetType = string

/*
	types and functions for productId
*/

// isNotNullableString
type ContactSalesContactSalesGetProductIdAttributeType = *string

func getContactSalesContactSalesGetProductIdAttributeTypeOk(arg ContactSalesContactSalesGetProductIdAttributeType) (ret ContactSalesContactSalesGetProductIdRetType, ok bool) {
	if arg == nil {
		return ret, false
	}
	return *arg, true
}

func setContactSalesContactSalesGetProductIdAttributeType(arg *ContactSalesContactSalesGetProductIdAttributeType, val ContactSalesContactSalesGetProductIdRetType) {
	*arg = &val
}

type ContactSalesContactSalesGetProductIdArgType = string
type ContactSalesContactSalesGetProductIdRetType = string

// ContactSalesContactSales struct for ContactSalesContactSales
type ContactSalesContactSales struct {
	// The company name.
	// REQUIRED
	CompanyName ContactSalesContactSalesGetCompanyNameAttributeType `json:"companyName"`
	// The contact e-mail address.
	// REQUIRED
	ContactEmail ContactSalesContactSalesGetContactEmailAttributeType `json:"contactEmail"`
	// The full name of the contact person.
	// REQUIRED
	FullName ContactSalesContactSalesGetFullNameAttributeType `json:"fullName"`
	// The message content.
	// REQUIRED
	Message ContactSalesContactSalesGetMessageAttributeType `json:"message"`
	// The product ID.
	// REQUIRED
	ProductId ContactSalesContactSalesGetProductIdAttributeType `json:"productId"`
}

type _ContactSalesContactSales ContactSalesContactSales

// NewContactSalesContactSales instantiates a new ContactSalesContactSales object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactSalesContactSales(companyName ContactSalesContactSalesGetCompanyNameArgType, contactEmail ContactSalesContactSalesGetContactEmailArgType, fullName ContactSalesContactSalesGetFullNameArgType, message ContactSalesContactSalesGetMessageArgType, productId ContactSalesContactSalesGetProductIdArgType) *ContactSalesContactSales {
	this := ContactSalesContactSales{}
	setContactSalesContactSalesGetCompanyNameAttributeType(&this.CompanyName, companyName)
	setContactSalesContactSalesGetContactEmailAttributeType(&this.ContactEmail, contactEmail)
	setContactSalesContactSalesGetFullNameAttributeType(&this.FullName, fullName)
	setContactSalesContactSalesGetMessageAttributeType(&this.Message, message)
	setContactSalesContactSalesGetProductIdAttributeType(&this.ProductId, productId)
	return &this
}

// NewContactSalesContactSalesWithDefaults instantiates a new ContactSalesContactSales object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactSalesContactSalesWithDefaults() *ContactSalesContactSales {
	this := ContactSalesContactSales{}
	return &this
}

// GetCompanyName returns the CompanyName field value
func (o *ContactSalesContactSales) GetCompanyName() (ret ContactSalesContactSalesGetCompanyNameRetType) {
	ret, _ = o.GetCompanyNameOk()
	return ret
}

// GetCompanyNameOk returns a tuple with the CompanyName field value
// and a boolean to check if the value has been set.
func (o *ContactSalesContactSales) GetCompanyNameOk() (ret ContactSalesContactSalesGetCompanyNameRetType, ok bool) {
	return getContactSalesContactSalesGetCompanyNameAttributeTypeOk(o.CompanyName)
}

// SetCompanyName sets field value
func (o *ContactSalesContactSales) SetCompanyName(v ContactSalesContactSalesGetCompanyNameRetType) {
	setContactSalesContactSalesGetCompanyNameAttributeType(&o.CompanyName, v)
}

// GetContactEmail returns the ContactEmail field value
func (o *ContactSalesContactSales) GetContactEmail() (ret ContactSalesContactSalesGetContactEmailRetType) {
	ret, _ = o.GetContactEmailOk()
	return ret
}

// GetContactEmailOk returns a tuple with the ContactEmail field value
// and a boolean to check if the value has been set.
func (o *ContactSalesContactSales) GetContactEmailOk() (ret ContactSalesContactSalesGetContactEmailRetType, ok bool) {
	return getContactSalesContactSalesGetContactEmailAttributeTypeOk(o.ContactEmail)
}

// SetContactEmail sets field value
func (o *ContactSalesContactSales) SetContactEmail(v ContactSalesContactSalesGetContactEmailRetType) {
	setContactSalesContactSalesGetContactEmailAttributeType(&o.ContactEmail, v)
}

// GetFullName returns the FullName field value
func (o *ContactSalesContactSales) GetFullName() (ret ContactSalesContactSalesGetFullNameRetType) {
	ret, _ = o.GetFullNameOk()
	return ret
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *ContactSalesContactSales) GetFullNameOk() (ret ContactSalesContactSalesGetFullNameRetType, ok bool) {
	return getContactSalesContactSalesGetFullNameAttributeTypeOk(o.FullName)
}

// SetFullName sets field value
func (o *ContactSalesContactSales) SetFullName(v ContactSalesContactSalesGetFullNameRetType) {
	setContactSalesContactSalesGetFullNameAttributeType(&o.FullName, v)
}

// GetMessage returns the Message field value
func (o *ContactSalesContactSales) GetMessage() (ret ContactSalesContactSalesGetMessageRetType) {
	ret, _ = o.GetMessageOk()
	return ret
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ContactSalesContactSales) GetMessageOk() (ret ContactSalesContactSalesGetMessageRetType, ok bool) {
	return getContactSalesContactSalesGetMessageAttributeTypeOk(o.Message)
}

// SetMessage sets field value
func (o *ContactSalesContactSales) SetMessage(v ContactSalesContactSalesGetMessageRetType) {
	setContactSalesContactSalesGetMessageAttributeType(&o.Message, v)
}

// GetProductId returns the ProductId field value
func (o *ContactSalesContactSales) GetProductId() (ret ContactSalesContactSalesGetProductIdRetType) {
	ret, _ = o.GetProductIdOk()
	return ret
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *ContactSalesContactSales) GetProductIdOk() (ret ContactSalesContactSalesGetProductIdRetType, ok bool) {
	return getContactSalesContactSalesGetProductIdAttributeTypeOk(o.ProductId)
}

// SetProductId sets field value
func (o *ContactSalesContactSales) SetProductId(v ContactSalesContactSalesGetProductIdRetType) {
	setContactSalesContactSalesGetProductIdAttributeType(&o.ProductId, v)
}

func (o ContactSalesContactSales) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if val, ok := getContactSalesContactSalesGetCompanyNameAttributeTypeOk(o.CompanyName); ok {
		toSerialize["CompanyName"] = val
	}
	if val, ok := getContactSalesContactSalesGetContactEmailAttributeTypeOk(o.ContactEmail); ok {
		toSerialize["ContactEmail"] = val
	}
	if val, ok := getContactSalesContactSalesGetFullNameAttributeTypeOk(o.FullName); ok {
		toSerialize["FullName"] = val
	}
	if val, ok := getContactSalesContactSalesGetMessageAttributeTypeOk(o.Message); ok {
		toSerialize["Message"] = val
	}
	if val, ok := getContactSalesContactSalesGetProductIdAttributeTypeOk(o.ProductId); ok {
		toSerialize["ProductId"] = val
	}
	return toSerialize, nil
}

type NullableContactSalesContactSales struct {
	value *ContactSalesContactSales
	isSet bool
}

func (v NullableContactSalesContactSales) Get() *ContactSalesContactSales {
	return v.value
}

func (v *NullableContactSalesContactSales) Set(val *ContactSalesContactSales) {
	v.value = val
	v.isSet = true
}

func (v NullableContactSalesContactSales) IsSet() bool {
	return v.isSet
}

func (v *NullableContactSalesContactSales) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactSalesContactSales(val *ContactSalesContactSales) *NullableContactSalesContactSales {
	return &NullableContactSalesContactSales{value: val, isSet: true}
}

func (v NullableContactSalesContactSales) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactSalesContactSales) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
