/*
STACKIT CDN API (DEPRECATED)

**DEPRECATED:** This API version (1beta.0.0) is deprecated. Please migrate to the version (v1).  API used to create and manage your CDN distributions.

API version: 1beta.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1betaapi

import (
	"context"
)

// assert the implementation matches the interface
var _ DefaultAPI = &DefaultAPIServiceMock{}

// DefaultAPIServiceMock is meant to be used for testing only as a replacement for DefaultAPIService.
// By default all FooExecute() implementations are a no-op. Behavior of the mock can be customized by populating the callbacks in this struct.
type DefaultAPIServiceMock struct {
	// Deprecated: CreateDistributionExecuteMock can be populated to implement the behavior of the CreateDistributionExecute function of this mock
	CreateDistributionExecuteMock *func(r ApiCreateDistributionRequest) (*CreateDistributionResponse, error)
	// Deprecated: DeleteCustomDomainExecuteMock can be populated to implement the behavior of the DeleteCustomDomainExecute function of this mock
	DeleteCustomDomainExecuteMock *func(r ApiDeleteCustomDomainRequest) (*DeleteCustomDomainResponse, error)
	// Deprecated: DeleteDistributionExecuteMock can be populated to implement the behavior of the DeleteDistributionExecute function of this mock
	DeleteDistributionExecuteMock *func(r ApiDeleteDistributionRequest) (*DeleteDistributionResponse, error)
	// Deprecated: FindCachePathsExecuteMock can be populated to implement the behavior of the FindCachePathsExecute function of this mock
	FindCachePathsExecuteMock *func(r ApiFindCachePathsRequest) (*FindCachePathsResponse, error)
	// Deprecated: GetCacheInfoExecuteMock can be populated to implement the behavior of the GetCacheInfoExecute function of this mock
	GetCacheInfoExecuteMock *func(r ApiGetCacheInfoRequest) (*GetCacheInfoResponse, error)
	// Deprecated: GetCustomDomainExecuteMock can be populated to implement the behavior of the GetCustomDomainExecute function of this mock
	GetCustomDomainExecuteMock *func(r ApiGetCustomDomainRequest) (*GetCustomDomainResponse, error)
	// Deprecated: GetDistributionExecuteMock can be populated to implement the behavior of the GetDistributionExecute function of this mock
	GetDistributionExecuteMock *func(r ApiGetDistributionRequest) (*GetDistributionResponse, error)
	// Deprecated: GetLogsExecuteMock can be populated to implement the behavior of the GetLogsExecute function of this mock
	GetLogsExecuteMock *func(r ApiGetLogsRequest) (*GetLogsResponse, error)
	// Deprecated: GetLogsSearchFiltersExecuteMock can be populated to implement the behavior of the GetLogsSearchFiltersExecute function of this mock
	GetLogsSearchFiltersExecuteMock *func(r ApiGetLogsSearchFiltersRequest) (*GetLogsSearchFiltersResponse, error)
	// Deprecated: GetStatisticsExecuteMock can be populated to implement the behavior of the GetStatisticsExecute function of this mock
	GetStatisticsExecuteMock *func(r ApiGetStatisticsRequest) (*GetStatisticsResponse, error)
	// Deprecated: ListDistributionsExecuteMock can be populated to implement the behavior of the ListDistributionsExecute function of this mock
	ListDistributionsExecuteMock *func(r ApiListDistributionsRequest) (*ListDistributionsResponse, error)
	// Deprecated: ListWAFCollectionsExecuteMock can be populated to implement the behavior of the ListWAFCollectionsExecute function of this mock
	ListWAFCollectionsExecuteMock *func(r ApiListWAFCollectionsRequest) (*ListWAFCollectionsResponse, error)
	// Deprecated: PatchDistributionExecuteMock can be populated to implement the behavior of the PatchDistributionExecute function of this mock
	PatchDistributionExecuteMock *func(r ApiPatchDistributionRequest) (*PatchDistributionResponse, error)
	// Deprecated: PurgeCacheExecuteMock can be populated to implement the behavior of the PurgeCacheExecute function of this mock
	PurgeCacheExecuteMock *func(r ApiPurgeCacheRequest) (map[string]interface{}, error)
	// Deprecated: PutCustomDomainExecuteMock can be populated to implement the behavior of the PutCustomDomainExecute function of this mock
	PutCustomDomainExecuteMock *func(r ApiPutCustomDomainRequest) (*PutCustomDomainResponse, error)
}

// Deprecated
func (a DefaultAPIServiceMock) CreateDistribution(ctx context.Context, projectId string) ApiCreateDistributionRequest {
	return ApiCreateDistributionRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Deprecated: CreateDistributionExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the CreateDistributionExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) CreateDistributionExecute(r ApiCreateDistributionRequest) (*CreateDistributionResponse, error) {
	if a.CreateDistributionExecuteMock == nil {
		var localVarReturnValue *CreateDistributionResponse
		return localVarReturnValue, nil
	}

	return (*a.CreateDistributionExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) DeleteCustomDomain(ctx context.Context, projectId string, distributionId string, domain string) ApiDeleteCustomDomainRequest {
	return ApiDeleteCustomDomainRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
		domain:         domain,
	}
}

// Deprecated: DeleteCustomDomainExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteCustomDomainExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteCustomDomainExecute(r ApiDeleteCustomDomainRequest) (*DeleteCustomDomainResponse, error) {
	if a.DeleteCustomDomainExecuteMock == nil {
		var localVarReturnValue *DeleteCustomDomainResponse
		return localVarReturnValue, nil
	}

	return (*a.DeleteCustomDomainExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) DeleteDistribution(ctx context.Context, projectId string, distributionId string) ApiDeleteDistributionRequest {
	return ApiDeleteDistributionRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: DeleteDistributionExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteDistributionExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteDistributionExecute(r ApiDeleteDistributionRequest) (*DeleteDistributionResponse, error) {
	if a.DeleteDistributionExecuteMock == nil {
		var localVarReturnValue *DeleteDistributionResponse
		return localVarReturnValue, nil
	}

	return (*a.DeleteDistributionExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) FindCachePaths(ctx context.Context, projectId string, distributionId string) ApiFindCachePathsRequest {
	return ApiFindCachePathsRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: FindCachePathsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the FindCachePathsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) FindCachePathsExecute(r ApiFindCachePathsRequest) (*FindCachePathsResponse, error) {
	if a.FindCachePathsExecuteMock == nil {
		var localVarReturnValue *FindCachePathsResponse
		return localVarReturnValue, nil
	}

	return (*a.FindCachePathsExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetCacheInfo(ctx context.Context, projectId string, distributionId string) ApiGetCacheInfoRequest {
	return ApiGetCacheInfoRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: GetCacheInfoExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetCacheInfoExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetCacheInfoExecute(r ApiGetCacheInfoRequest) (*GetCacheInfoResponse, error) {
	if a.GetCacheInfoExecuteMock == nil {
		var localVarReturnValue *GetCacheInfoResponse
		return localVarReturnValue, nil
	}

	return (*a.GetCacheInfoExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetCustomDomain(ctx context.Context, projectId string, distributionId string, domain string) ApiGetCustomDomainRequest {
	return ApiGetCustomDomainRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
		domain:         domain,
	}
}

// Deprecated: GetCustomDomainExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetCustomDomainExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetCustomDomainExecute(r ApiGetCustomDomainRequest) (*GetCustomDomainResponse, error) {
	if a.GetCustomDomainExecuteMock == nil {
		var localVarReturnValue *GetCustomDomainResponse
		return localVarReturnValue, nil
	}

	return (*a.GetCustomDomainExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetDistribution(ctx context.Context, projectId string, distributionId string) ApiGetDistributionRequest {
	return ApiGetDistributionRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: GetDistributionExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetDistributionExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetDistributionExecute(r ApiGetDistributionRequest) (*GetDistributionResponse, error) {
	if a.GetDistributionExecuteMock == nil {
		var localVarReturnValue *GetDistributionResponse
		return localVarReturnValue, nil
	}

	return (*a.GetDistributionExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetLogs(ctx context.Context, projectId string, distributionId string) ApiGetLogsRequest {
	return ApiGetLogsRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: GetLogsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetLogsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetLogsExecute(r ApiGetLogsRequest) (*GetLogsResponse, error) {
	if a.GetLogsExecuteMock == nil {
		var localVarReturnValue *GetLogsResponse
		return localVarReturnValue, nil
	}

	return (*a.GetLogsExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetLogsSearchFilters(ctx context.Context, projectId string, distributionId string) ApiGetLogsSearchFiltersRequest {
	return ApiGetLogsSearchFiltersRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: GetLogsSearchFiltersExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetLogsSearchFiltersExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetLogsSearchFiltersExecute(r ApiGetLogsSearchFiltersRequest) (*GetLogsSearchFiltersResponse, error) {
	if a.GetLogsSearchFiltersExecuteMock == nil {
		var localVarReturnValue *GetLogsSearchFiltersResponse
		return localVarReturnValue, nil
	}

	return (*a.GetLogsSearchFiltersExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) GetStatistics(ctx context.Context, projectId string, distributionId string) ApiGetStatisticsRequest {
	return ApiGetStatisticsRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: GetStatisticsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetStatisticsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetStatisticsExecute(r ApiGetStatisticsRequest) (*GetStatisticsResponse, error) {
	if a.GetStatisticsExecuteMock == nil {
		var localVarReturnValue *GetStatisticsResponse
		return localVarReturnValue, nil
	}

	return (*a.GetStatisticsExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) ListDistributions(ctx context.Context, projectId string) ApiListDistributionsRequest {
	return ApiListDistributionsRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Deprecated: ListDistributionsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListDistributionsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListDistributionsExecute(r ApiListDistributionsRequest) (*ListDistributionsResponse, error) {
	if a.ListDistributionsExecuteMock == nil {
		var localVarReturnValue *ListDistributionsResponse
		return localVarReturnValue, nil
	}

	return (*a.ListDistributionsExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) ListWAFCollections(ctx context.Context, projectId string) ApiListWAFCollectionsRequest {
	return ApiListWAFCollectionsRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Deprecated: ListWAFCollectionsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListWAFCollectionsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListWAFCollectionsExecute(r ApiListWAFCollectionsRequest) (*ListWAFCollectionsResponse, error) {
	if a.ListWAFCollectionsExecuteMock == nil {
		var localVarReturnValue *ListWAFCollectionsResponse
		return localVarReturnValue, nil
	}

	return (*a.ListWAFCollectionsExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) PatchDistribution(ctx context.Context, projectId string, distributionId string) ApiPatchDistributionRequest {
	return ApiPatchDistributionRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: PatchDistributionExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the PatchDistributionExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) PatchDistributionExecute(r ApiPatchDistributionRequest) (*PatchDistributionResponse, error) {
	if a.PatchDistributionExecuteMock == nil {
		var localVarReturnValue *PatchDistributionResponse
		return localVarReturnValue, nil
	}

	return (*a.PatchDistributionExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) PurgeCache(ctx context.Context, projectId string, distributionId string) ApiPurgeCacheRequest {
	return ApiPurgeCacheRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
	}
}

// Deprecated: PurgeCacheExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the PurgeCacheExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) PurgeCacheExecute(r ApiPurgeCacheRequest) (map[string]interface{}, error) {
	if a.PurgeCacheExecuteMock == nil {
		var localVarReturnValue map[string]interface{}
		return localVarReturnValue, nil
	}

	return (*a.PurgeCacheExecuteMock)(r)
}

// Deprecated
func (a DefaultAPIServiceMock) PutCustomDomain(ctx context.Context, projectId string, distributionId string, domain string) ApiPutCustomDomainRequest {
	return ApiPutCustomDomainRequest{
		ApiService:     a,
		ctx:            ctx,
		projectId:      projectId,
		distributionId: distributionId,
		domain:         domain,
	}
}

// Deprecated: PutCustomDomainExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the PutCustomDomainExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) PutCustomDomainExecute(r ApiPutCustomDomainRequest) (*PutCustomDomainResponse, error) {
	if a.PutCustomDomainExecuteMock == nil {
		var localVarReturnValue *PutCustomDomainResponse
		return localVarReturnValue, nil
	}

	return (*a.PutCustomDomainExecuteMock)(r)
}
