/*
STACKIT Functions Core API

This API provides endpoints for managing STACKIT Functions.

API version: 1alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alphaapi

import (
	"encoding/json"
)

// checks if the ListPullSecrets type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPullSecrets{}

// ListPullSecrets struct for ListPullSecrets
type ListPullSecrets struct {
	// Token for the next page of results.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// List of oci registries pull secrets associated with the project.
	PullCredentials      []PullSecret `json:"pull_credentials,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListPullSecrets ListPullSecrets

// NewListPullSecrets instantiates a new ListPullSecrets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPullSecrets() *ListPullSecrets {
	this := ListPullSecrets{}
	return &this
}

// NewListPullSecretsWithDefaults instantiates a new ListPullSecrets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPullSecretsWithDefaults() *ListPullSecrets {
	this := ListPullSecrets{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListPullSecrets) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPullSecrets) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListPullSecrets) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListPullSecrets) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetPullCredentials returns the PullCredentials field value if set, zero value otherwise.
func (o *ListPullSecrets) GetPullCredentials() []PullSecret {
	if o == nil || IsNil(o.PullCredentials) {
		var ret []PullSecret
		return ret
	}
	return o.PullCredentials
}

// GetPullCredentialsOk returns a tuple with the PullCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPullSecrets) GetPullCredentialsOk() ([]PullSecret, bool) {
	if o == nil || IsNil(o.PullCredentials) {
		return nil, false
	}
	return o.PullCredentials, true
}

// HasPullCredentials returns a boolean if a field has been set.
func (o *ListPullSecrets) HasPullCredentials() bool {
	if o != nil && !IsNil(o.PullCredentials) {
		return true
	}

	return false
}

// SetPullCredentials gets a reference to the given []PullSecret and assigns it to the PullCredentials field.
func (o *ListPullSecrets) SetPullCredentials(v []PullSecret) {
	o.PullCredentials = v
}

func (o ListPullSecrets) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPullSecrets) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	if !IsNil(o.PullCredentials) {
		toSerialize["pull_credentials"] = o.PullCredentials
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListPullSecrets) UnmarshalJSON(data []byte) (err error) {
	varListPullSecrets := _ListPullSecrets{}

	err = json.Unmarshal(data, &varListPullSecrets)

	if err != nil {
		return err
	}

	*o = ListPullSecrets(varListPullSecrets)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next_page_token")
		delete(additionalProperties, "pull_credentials")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListPullSecrets struct {
	value *ListPullSecrets
	isSet bool
}

func (v NullableListPullSecrets) Get() *ListPullSecrets {
	return v.value
}

func (v *NullableListPullSecrets) Set(val *ListPullSecrets) {
	v.value = val
	v.isSet = true
}

func (v NullableListPullSecrets) IsSet() bool {
	return v.isSet
}

func (v *NullableListPullSecrets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPullSecrets(val *ListPullSecrets) *NullableListPullSecrets {
	return &NullableListPullSecrets{value: val, isSet: true}
}

func (v NullableListPullSecrets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPullSecrets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
