/*
STACKIT Object Storage API

STACKIT API to manage the Object Storage

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2api

import (
	"context"
)

// assert the implementation matches the interface
var _ DefaultAPI = &DefaultAPIServiceMock{}

// DefaultAPIServiceMock is meant to be used for testing only as a replacement for DefaultAPIService.
// By default all FooExecute() implementations are a no-op. Behavior of the mock can be customized by populating the callbacks in this struct.
type DefaultAPIServiceMock struct {
	// CreateAccessKeyExecuteMock can be populated to implement the behavior of the CreateAccessKeyExecute function of this mock
	CreateAccessKeyExecuteMock *func(r ApiCreateAccessKeyRequest) (*CreateAccessKeyResponse, error)
	// CreateBucketExecuteMock can be populated to implement the behavior of the CreateBucketExecute function of this mock
	CreateBucketExecuteMock *func(r ApiCreateBucketRequest) (*CreateBucketResponse, error)
	// CreateCredentialsGroupExecuteMock can be populated to implement the behavior of the CreateCredentialsGroupExecute function of this mock
	CreateCredentialsGroupExecuteMock *func(r ApiCreateCredentialsGroupRequest) (*CreateCredentialsGroupResponse, error)
	// DeleteAccessKeyExecuteMock can be populated to implement the behavior of the DeleteAccessKeyExecute function of this mock
	DeleteAccessKeyExecuteMock *func(r ApiDeleteAccessKeyRequest) (*DeleteAccessKeyResponse, error)
	// DeleteBucketExecuteMock can be populated to implement the behavior of the DeleteBucketExecute function of this mock
	DeleteBucketExecuteMock *func(r ApiDeleteBucketRequest) (*DeleteBucketResponse, error)
	// DeleteCredentialsGroupExecuteMock can be populated to implement the behavior of the DeleteCredentialsGroupExecute function of this mock
	DeleteCredentialsGroupExecuteMock *func(r ApiDeleteCredentialsGroupRequest) (*DeleteCredentialsGroupResponse, error)
	// DisableServiceExecuteMock can be populated to implement the behavior of the DisableServiceExecute function of this mock
	DisableServiceExecuteMock *func(r ApiDisableServiceRequest) (*ProjectStatus, error)
	// EnableServiceExecuteMock can be populated to implement the behavior of the EnableServiceExecute function of this mock
	EnableServiceExecuteMock *func(r ApiEnableServiceRequest) (*ProjectStatus, error)
	// GetBucketExecuteMock can be populated to implement the behavior of the GetBucketExecute function of this mock
	GetBucketExecuteMock *func(r ApiGetBucketRequest) (*GetBucketResponse, error)
	// GetServiceStatusExecuteMock can be populated to implement the behavior of the GetServiceStatusExecute function of this mock
	GetServiceStatusExecuteMock *func(r ApiGetServiceStatusRequest) (*ProjectStatus, error)
	// ListAccessKeysExecuteMock can be populated to implement the behavior of the ListAccessKeysExecute function of this mock
	ListAccessKeysExecuteMock *func(r ApiListAccessKeysRequest) (*ListAccessKeysResponse, error)
	// ListBucketsExecuteMock can be populated to implement the behavior of the ListBucketsExecute function of this mock
	ListBucketsExecuteMock *func(r ApiListBucketsRequest) (*ListBucketsResponse, error)
	// ListCredentialsGroupsExecuteMock can be populated to implement the behavior of the ListCredentialsGroupsExecute function of this mock
	ListCredentialsGroupsExecuteMock *func(r ApiListCredentialsGroupsRequest) (*ListCredentialsGroupsResponse, error)
}

func (a DefaultAPIServiceMock) CreateAccessKey(ctx context.Context, projectId string, region string) ApiCreateAccessKeyRequest {
	return ApiCreateAccessKeyRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// CreateAccessKeyExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the CreateAccessKeyExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) CreateAccessKeyExecute(r ApiCreateAccessKeyRequest) (*CreateAccessKeyResponse, error) {
	if a.CreateAccessKeyExecuteMock == nil {
		var localVarReturnValue *CreateAccessKeyResponse
		return localVarReturnValue, nil
	}

	return (*a.CreateAccessKeyExecuteMock)(r)
}

func (a DefaultAPIServiceMock) CreateBucket(ctx context.Context, projectId string, region string, bucketName string) ApiCreateBucketRequest {
	return ApiCreateBucketRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
		bucketName: bucketName,
	}
}

// CreateBucketExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the CreateBucketExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) CreateBucketExecute(r ApiCreateBucketRequest) (*CreateBucketResponse, error) {
	if a.CreateBucketExecuteMock == nil {
		var localVarReturnValue *CreateBucketResponse
		return localVarReturnValue, nil
	}

	return (*a.CreateBucketExecuteMock)(r)
}

func (a DefaultAPIServiceMock) CreateCredentialsGroup(ctx context.Context, projectId string, region string) ApiCreateCredentialsGroupRequest {
	return ApiCreateCredentialsGroupRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// CreateCredentialsGroupExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the CreateCredentialsGroupExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) CreateCredentialsGroupExecute(r ApiCreateCredentialsGroupRequest) (*CreateCredentialsGroupResponse, error) {
	if a.CreateCredentialsGroupExecuteMock == nil {
		var localVarReturnValue *CreateCredentialsGroupResponse
		return localVarReturnValue, nil
	}

	return (*a.CreateCredentialsGroupExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DeleteAccessKey(ctx context.Context, projectId string, region string, keyId string) ApiDeleteAccessKeyRequest {
	return ApiDeleteAccessKeyRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
		keyId:      keyId,
	}
}

// DeleteAccessKeyExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteAccessKeyExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteAccessKeyExecute(r ApiDeleteAccessKeyRequest) (*DeleteAccessKeyResponse, error) {
	if a.DeleteAccessKeyExecuteMock == nil {
		var localVarReturnValue *DeleteAccessKeyResponse
		return localVarReturnValue, nil
	}

	return (*a.DeleteAccessKeyExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DeleteBucket(ctx context.Context, projectId string, region string, bucketName string) ApiDeleteBucketRequest {
	return ApiDeleteBucketRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
		bucketName: bucketName,
	}
}

// DeleteBucketExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteBucketExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteBucketExecute(r ApiDeleteBucketRequest) (*DeleteBucketResponse, error) {
	if a.DeleteBucketExecuteMock == nil {
		var localVarReturnValue *DeleteBucketResponse
		return localVarReturnValue, nil
	}

	return (*a.DeleteBucketExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DeleteCredentialsGroup(ctx context.Context, projectId string, region string, groupId string) ApiDeleteCredentialsGroupRequest {
	return ApiDeleteCredentialsGroupRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
		groupId:    groupId,
	}
}

// DeleteCredentialsGroupExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DeleteCredentialsGroupExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DeleteCredentialsGroupExecute(r ApiDeleteCredentialsGroupRequest) (*DeleteCredentialsGroupResponse, error) {
	if a.DeleteCredentialsGroupExecuteMock == nil {
		var localVarReturnValue *DeleteCredentialsGroupResponse
		return localVarReturnValue, nil
	}

	return (*a.DeleteCredentialsGroupExecuteMock)(r)
}

func (a DefaultAPIServiceMock) DisableService(ctx context.Context, projectId string, region string) ApiDisableServiceRequest {
	return ApiDisableServiceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// DisableServiceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the DisableServiceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) DisableServiceExecute(r ApiDisableServiceRequest) (*ProjectStatus, error) {
	if a.DisableServiceExecuteMock == nil {
		var localVarReturnValue *ProjectStatus
		return localVarReturnValue, nil
	}

	return (*a.DisableServiceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) EnableService(ctx context.Context, projectId string, region string) ApiEnableServiceRequest {
	return ApiEnableServiceRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// EnableServiceExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the EnableServiceExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) EnableServiceExecute(r ApiEnableServiceRequest) (*ProjectStatus, error) {
	if a.EnableServiceExecuteMock == nil {
		var localVarReturnValue *ProjectStatus
		return localVarReturnValue, nil
	}

	return (*a.EnableServiceExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetBucket(ctx context.Context, projectId string, region string, bucketName string) ApiGetBucketRequest {
	return ApiGetBucketRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
		bucketName: bucketName,
	}
}

// GetBucketExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetBucketExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetBucketExecute(r ApiGetBucketRequest) (*GetBucketResponse, error) {
	if a.GetBucketExecuteMock == nil {
		var localVarReturnValue *GetBucketResponse
		return localVarReturnValue, nil
	}

	return (*a.GetBucketExecuteMock)(r)
}

func (a DefaultAPIServiceMock) GetServiceStatus(ctx context.Context, projectId string, region string) ApiGetServiceStatusRequest {
	return ApiGetServiceStatusRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// GetServiceStatusExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the GetServiceStatusExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) GetServiceStatusExecute(r ApiGetServiceStatusRequest) (*ProjectStatus, error) {
	if a.GetServiceStatusExecuteMock == nil {
		var localVarReturnValue *ProjectStatus
		return localVarReturnValue, nil
	}

	return (*a.GetServiceStatusExecuteMock)(r)
}

func (a DefaultAPIServiceMock) ListAccessKeys(ctx context.Context, projectId string, region string) ApiListAccessKeysRequest {
	return ApiListAccessKeysRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// ListAccessKeysExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListAccessKeysExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListAccessKeysExecute(r ApiListAccessKeysRequest) (*ListAccessKeysResponse, error) {
	if a.ListAccessKeysExecuteMock == nil {
		var localVarReturnValue *ListAccessKeysResponse
		return localVarReturnValue, nil
	}

	return (*a.ListAccessKeysExecuteMock)(r)
}

func (a DefaultAPIServiceMock) ListBuckets(ctx context.Context, projectId string, region string) ApiListBucketsRequest {
	return ApiListBucketsRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// ListBucketsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListBucketsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListBucketsExecute(r ApiListBucketsRequest) (*ListBucketsResponse, error) {
	if a.ListBucketsExecuteMock == nil {
		var localVarReturnValue *ListBucketsResponse
		return localVarReturnValue, nil
	}

	return (*a.ListBucketsExecuteMock)(r)
}

func (a DefaultAPIServiceMock) ListCredentialsGroups(ctx context.Context, projectId string, region string) ApiListCredentialsGroupsRequest {
	return ApiListCredentialsGroupsRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		region:     region,
	}
}

// ListCredentialsGroupsExecute is a no-op by default and will return only return nil values. Behavior can be controlled by populating the ListCredentialsGroupsExecuteMock field in the DefaultAPIServiceMock struct.
func (a DefaultAPIServiceMock) ListCredentialsGroupsExecute(r ApiListCredentialsGroupsRequest) (*ListCredentialsGroupsResponse, error) {
	if a.ListCredentialsGroupsExecuteMock == nil {
		var localVarReturnValue *ListCredentialsGroupsResponse
		return localVarReturnValue, nil
	}

	return (*a.ListCredentialsGroupsExecuteMock)(r)
}
