/*
STACKIT Telemetry Link API

This API provides endpoints for managing Telemetry Links. The Telemetry Link enables Log Routing towards a defined Telemetry Router.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1api

import (
	"encoding/json"
	"fmt"
)

// BackflushJobResponseRegionId The STACKIT region name the resource is located in.
type BackflushJobResponseRegionId string

// List of backflushJobResponse_regionId
const (
	BACKFLUSHJOBRESPONSEREGIONID_EU01                     BackflushJobResponseRegionId = "eu01"
	BACKFLUSHJOBRESPONSEREGIONID_EU02                     BackflushJobResponseRegionId = "eu02"
	BACKFLUSHJOBRESPONSEREGIONID_UNKNOWN_DEFAULT_OPEN_API BackflushJobResponseRegionId = "unknown_default_open_api"
)

// All allowed values of BackflushJobResponseRegionId enum
var AllowedBackflushJobResponseRegionIdEnumValues = []BackflushJobResponseRegionId{
	"eu01",
	"eu02",
	"unknown_default_open_api",
}

func (v *BackflushJobResponseRegionId) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BackflushJobResponseRegionId(value)
	for _, existing := range AllowedBackflushJobResponseRegionIdEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = BACKFLUSHJOBRESPONSEREGIONID_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewBackflushJobResponseRegionIdFromValue returns a pointer to a valid BackflushJobResponseRegionId
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBackflushJobResponseRegionIdFromValue(v string) (*BackflushJobResponseRegionId, error) {
	ev := BackflushJobResponseRegionId(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BackflushJobResponseRegionId: valid values are %v", v, AllowedBackflushJobResponseRegionIdEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BackflushJobResponseRegionId) IsValid() bool {
	for _, existing := range AllowedBackflushJobResponseRegionIdEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to backflushJobResponse_regionId value
func (v BackflushJobResponseRegionId) Ptr() *BackflushJobResponseRegionId {
	return &v
}

type NullableBackflushJobResponseRegionId struct {
	value *BackflushJobResponseRegionId
	isSet bool
}

func (v NullableBackflushJobResponseRegionId) Get() *BackflushJobResponseRegionId {
	return v.value
}

func (v *NullableBackflushJobResponseRegionId) Set(val *BackflushJobResponseRegionId) {
	v.value = val
	v.isSet = true
}

func (v NullableBackflushJobResponseRegionId) IsSet() bool {
	return v.isSet
}

func (v *NullableBackflushJobResponseRegionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackflushJobResponseRegionId(val *BackflushJobResponseRegionId) *NullableBackflushJobResponseRegionId {
	return &NullableBackflushJobResponseRegionId{value: val, isSet: true}
}

func (v NullableBackflushJobResponseRegionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackflushJobResponseRegionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
