name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:   # REMOVE ME

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN_TEST }}
        env:
          LOG_LEVEL: 'DEBUG'