name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:   # REMOVE ME

jobs:
  renovate:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}